"""ErrorTags for simplebench.reporters.choices"""
from simplebench.exceptions.base import ErrorTag
from simplebench.enums import enum_docstrings


@enum_docstrings
class ChoicesErrorTag(ErrorTag):
    """ErrorTags for simplebench.reporters.choices."""
    # reporters.Choice() tags
    CHOICE_INVALID_REPORTER_ARG_TYPE = "CHOICE_INVALID_REPORTER_ARG_TYPE"
    """Something other than a Reporter subclass was passed as the reporter arg"""
    CHOICE_INVALID_FLAGS_ARGS_VALUE = "CHOICE_EMPTY_FLAGS_ARGS_VALUE"
    """The flags arg cannot be an empty sequence or contain strings with whitespace"""
    CHOICE_INVALID_FLAGS_ARG_TYPE = "CHOICE_INVALID_FLAGS_ARG_TYPE"
    """Something other than a sequence of string was passed as the flags arg"""
    CHOICE_INVALID_NAME_ARG_TYPE = "CHOICE_INVALID_NAME_ARG_TYPE"
    """Something other than a string was passed as the name arg"""
    CHOICE_EMPTY_NAME_ARG_VALUE = "CHOICE_EMPTY_NAME_ARG_VALUE"
    """The name arg cannot be an empty string"""
    CHOICE_INVALID_DESCRIPTION_ARG_TYPE = "CHOICE_INVALID_DESCRIPTION_ARG_TYPE"
    """Something other than a string was passed as the description arg"""
    CHOICE_EMPTY_DESCRIPTION_ARG_VALUE = "CHOICE_EMPTY_DESCRIPTION_ARG_VALUE"
    """The description arg cannot be an empty string"""
    CHOICE_INVALID_SECTIONS_ARG_TYPE = "CHOICE_INVALID_SECTIONS_ARG_TYPE"
    """Something other than a sequence of Section enums was passed as the sections arg"""
    CHOICE_EMPTY_SECTIONS_ARG_VALUE = "CHOICE_EMPTY_SECTIONS_ARG_VALUE"
    """The sections arg cannot be an empty sequence"""
    CHOICE_INVALID_TARGETS_ARG_TYPE = "CHOICE_INVALID_TARGETS_ARG_TYPE"
    """Something other than a sequence of Target enums was passed as the targets arg"""
    CHOICE_EMPTY_TARGETS_ARG_VALUE = "CHOICE_EMPTY_TARGETS_ARG_VALUE"
    """The targets arg cannot be an empty sequence"""
    CHOICE_INVALID_FORMATS_ARG_TYPE = "CHOICE_INVALID_FORMATS_ARG_TYPE"
    """Something other than a sequence of Format enums was passed as the formats arg"""
    CHOICE_EMPTY_FORMATS_ARG_VALUE = "CHOICE_EMPTY_FORMATS_ARG_VALUE"
    """The formats arg cannot be an empty sequence"""
    CHOICE_INVALID_OPTIONS_ARG_TYPE = "CHOICE_INVALID_OPTIONS_ARG_TYPE"
    """Something other than a ReporterOptions instance was passed as the options arg"""
    CHOICE_INVALID_FLAG_TYPE_ARG_TYPE = "CHOICE_INVALID_FLAG_TYPE_ARG_TYPE"
    """Something other than a FlagType enum was passed as the flag_type arg"""

    # reporters.Choices() tags
    CHOICES_INVALID_CHOICES_ARG_TYPE = "CHOICES_INVALID_CHOICES_ARG_TYPE"
    """Something other than a Sequence of Choice instances or a Choices instance was passed as the choices arg"""
    CHOICES_INVALID_CHOICES_ARG_SEQUENCE_TYPE = "CHOICES_INVALID_CHOICES_ARG_SEQUENCE_TYPE"
    """Something other than a Sequence was passed as the choices arg"""
    CHOICES_INVALID_CHOICES_ITEM_VALUE = "CHOICES_INVALID_CHOICES_ITEM_VALUE"
    """Something other than a Choice instance was found in the Sequence passed as the choices arg"""
    CHOICES_ADD_INVALID_CHOICE_ARG_TYPE = "CHOICES_ADD_INVALID_CHOICE_ARG_TYPE"
    """Something other than a Choice instance was passed to the Choices.add() method"""
    CHOICES_ADD_DUPLICATE_CHOICE_NAME = "CHOICES_ADD_DUPLICATE_CHOICE_NAME"
    """A Choice with the same name already exists in the Choices instance"""
    CHOICES_ADD_DUPLICATE_CLI_ARG = "CHOICES_ADD_DUPLICATE_CLI_ARG"
    """A Choice with the same CLI argument already exists in the Choices instance"""
    CHOICES_EXTEND_INVALID_CHOICES_ARG_SEQUENCE_TYPE = "CHOICES_EXTEND_INVALID_CHOICES_ARG_SEQUENCE_TYPE"
    """Something other than a Sequence was passed to the Choices.extend() method"""
    CHOICES_EXTEND_INVALID_CHOICES_ITEM_VALUE = "CHOICES_EXTEND_INVALID_CHOICES_ITEM_VALUE"
    """Something other than a Choice instance was found in the Sequence passed to the Choices.extend() method"""
    CHOICES_EXTEND_DUPLICATE_CHOICE_NAME = "CHOICES_EXTEND_DUPLICATE_CHOICE_NAME"
    """A Choice with the same name already exists in the Choices instance"""
    CHOICES_EXTEND_DUPLICATE_CLI_ARG = "CHOICES_EXTEND_DUPLICATE_CLI_ARG"
    """A Choice with the same CLI argument already exists in the Choices instance"""
    CHOICES_GET_CHOICE_FOR_ARG_INVALID_ARG_TYPE = "CHOICES_GET_CHOICE_FOR_ARG_INVALID_ARG_TYPE"
    """Something other than a string was passed to the Choices.get_choice_for_arg() method"""
    CHOICES_GET_CHOICE_FOR_ARG_INVALID_ARG_VALUE = "CHOICES_GET_CHOICE_FOR_ARG_INVALID_ARG_VALUE"
    """No Choice with the given CLI argument exists in the Choices instance"""
    CHOICES_CHOICE_FOR_FLAG_INVALID_ARG = "CHOICES_CHOICE_FOR_FLAG_INVALID_ARG"
    """Something other than a string was passed to the Choices.choice_for_flag() method"""
    CHOICES_GET_CHOICE_BY_CLI_TAG_INVALID_ARG = "CHOICES_GET_CHOICE_BY_CLI_TAG_INVALID_ARG"
    """Something other than a string was passed to the Choices.get_choice_by_cli_tag() method"""
    CHOICES_ALL_CHOICE_FLAGS_INVALID_RETURN = "CHOICES_ALL_CHOICE_FLAGS_INVALID_RETURN"
    """Something other than a set of strings was returned from the Choices.all_choice_flags() method"""
    CHOICES_DELITEM_UNKNOWN_CHOICE_NAME = "CHOICES_DELITEM_UNKNOWN_CHOICE_NAME"
    """No Choice with the given name exists in the Choices instance"""
    CHOICES_ADD_DUPLICATE_CHOICE_FLAG = "CHOICES_ADD_DUPLICATE_CHOICE_FLAG"
    """A Choice with the same CLI argument already exists in the Choices instance"""
    CHOICES_SETITEM_INVALID_VALUE_TYPE = "CHOICES_SETITEM_INVALID_VALUE_TYPE"
    """Something other than a Choice instance was passed as the value to the Choices.__setitem__() method"""
    CHOICES_SETITEM_INVALID_KEY_TYPE = "CHOICES_SETITEM_INVALID_KEY_TYPE"
    """Something other than a string was passed as the key to the Choices.__setitem__() method"""
    CHOICES_SETITEM_KEY_NAME_MISMATCH = "CHOICES_SETITEM_KEY_NAME_MISMATCH"
    """The key passed to the Choices.__setitem__() method does not match the name attribute of the Choice instance"""
    CHOICES_SETITEM_DUPLICATE_CHOICE_NAME = "CHOICES_SETITEM_DUPLICATE_CHOICE_NAME"
    """A Choice with the same name already exists in the Choices instance"""
    CHOICES_SETITEM_DUPLICATE_CHOICE_FLAG = "CHOICES_SETITEM_DUPLICATE_CHOICE_FLAG"
    """A Choice with the same CLI argument flag already exists in the Choices instance"""
