"""Exceptions for the simplebench.reporters.interfaces module."""
from simplebench.exceptions.base import ErrorTag
from simplebench.enums import enum_docstrings


@enum_docstrings
class ReportersInterfacesErrorTag(ErrorTag):
    """ErrorTags for exceptions in the reporters.interfaces module."""
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    """The Reporter base class is an abstract base class and must be subclassed"""
    INIT_NOT_IMPLEMENTED = "INIT_NOT_IMPLEMENTED"
    """The Reporter base class cannot be instantiated directly"""
    CHOICES_NOT_IMPLEMENTED = "CHOICES_NOT_IMPLEMENTED"
    """The Reporter.choices property must be implemented in subclasses"""
    LOAD_CHOICES_NOT_IMPLEMENTED = "LOAD_CHOICES_NOT_IMPLEMENTED"
    """The Reporter._load_choices() method must be implemented in subclasses"""
    NAME_NOT_IMPLEMENTED = "NAME_NOT_IMPLEMENTED"
    """The Reporter.name property must be initialized as a str by subclasses"""
    NAME_INVALID_VALUE = "NAME_INVALID_VALUE"
    """The Reporter.name property must be initialized as a non-empty string by subclasses"""
    DESCRIPTION_NOT_IMPLEMENTED = "DESCRIPTION_NOT_IMPLEMENTED"
    """The Reporter.description property must be initialized as a str by subclasses"""
    DESCRIPTION_INVALID_VALUE = "DESCRIPTION_INVALID_VALUE"
    """The Reporter.description property must be initialized as a string by subclasses"""
    RUN_REPORT_NOT_IMPLEMENTED = "RUN_REPORT_NOT_IMPLEMENTED"
    """The Reporter.run_report() method must be implemented by subclasses"""
    ADD_FLAGS_NOT_IMPLEMENTED = "ADD_FLAGS_NOT_IMPLEMENTED"
    """The Reporter.add_flags_to_argparse() method must be implemented in subclasses"""
    ADD_FLAGS_UNSUPPORTED_FLAG_TYPE = "ADD_FLAGS_UNSUPPORTED_FLAG_TYPE"
    """The Reporter.add_flags_to_argparse() method only supports flags of type
    FlagType.BOOLEAN or FlagType.TARGET_LIST"""
    ADD_LIST_OF_TARGETS_FLAGS_INVALID_CHOICE_ARG_TYPE = (
        "ADD_LIST_OF_TARGETS_FLAGS_INVALID_CHOICE_ARG_TYPE")
    """Something other than a Choice instance was passed to the Reporter.add_list_of_targets_flags() method"""
    ADD_BOOLEAN_FLAGS_INVALID_CHOICE_ARG_TYPE = "ADD_BOOLEAN_FLAGS_INVALID_CHOICE_ARG_TYPE"
    """Something other than a Choice instance was passed to the Reporter.add_boolean_flags() method"""
    FORMATS_NOT_IMPLEMENTED = "FORMATS_NOT_IMPLEMENTED"
    """The Reporter.formats property must be implemented in subclasses"""
    INVALID_FORMATS_ENTRY_TYPE = "INVALID_FORMATS_ENTRY_TYPE"
    """Something other than a Format enum was found in the formats argument."""
    SECTIONS_NOT_IMPLEMENTED = "SECTIONS_NOT_IMPLEMENTED"
    """The Reporter.sections property must be implemented in subclasses"""
    INVALID_SECTIONS_ENTRY_TYPE = "INVALID_SECTIONS_ENTRY_TYPE"
    """Something other than a Section enum was found in the sections argument."""
    TARGETS_NOT_IMPLEMENTED = "TARGETS_NOT_IMPLEMENTED"
    """The Reporter.targets property must be implemented in subclasses"""
    INVALID_TARGETS_ENTRY_TYPE = "INVALID_TARGETS_ENTRY_TYPE"
    """Something other than a Target enum was found in the targets argument."""
    REPORT_INVALID_ARGS_ARG_TYPE = "REPORT_INVALID_ARGS_ARG_TYPE"
    """Something other than a Namespace instance was passed to the Reporter.report() method as the args argument"""
    REPORT_INVALID_CASE_ARG = "REPORT_INVALID_CASE_ARG"
    """Something other than a Case instance was passed to the Reporter.report() method"""
    REPORT_INVALID_CHOICE_ARG = "REPORT_INVALID_CHOICE_ARG"
    """Something other than a Choice instance was passed to the Reporter.report() method"""
    REPORT_INVALID_SESSION_ARG = "REPORT_INVALID_SESSION_ARG"
    """Something other than a Session instance was passed to the Reporter.report() method"""
    REPORT_INVALID_PATH_ARG = "REPORT_INVALID_PATH_ARG"
    """Something other than a Path instance was passed to the Reporter.report() method"""
    REPORT_INVALID_CALLBACK_ARG = "REPORT_INVALID_CALLBACK_ARG"
    """Something other than a callable was passed to the Reporter.report() method as the callback argument"""
    REPORT_UNSUPPORTED_SECTION = "REPORT_UNSUPPORTED_SECTION"
    """An unsupported Section was passed to the Reporter.report() method in the Choice.sections"""
    REPORT_UNSUPPORTED_TARGET = "REPORT_UNSUPPORTED_TARGET"
    """An unsupported Target was passed to the Reporter.report() method in the Choice.targets"""
    REPORT_UNSUPPORTED_FORMAT = "REPORT_UNSUPPORTED_FORMAT"
    """An unsupported Format was passed to the Reporter.report() method in the Choice.formats"""
    ADD_CHOICE_INVALID_ARG_TYPE = "ADD_CHOICE_INVALID_ARG_TYPE"
    """Something other than a Choice instance was passed to the Reporter.add_choice() method"""
    ADD_CHOICE_DUPLICATE_NAME = "ADD_CHOICE_DUPLICATE_NAME"
    """A Choice with the same name already exists in the Reporter instance"""
    ADD_CHOICE_DUPLICATE_CLI_ARG = "ADD_CHOICE_DUPLICATE_CLI_ARG"
    """A Choice with the same CLI argument already exists in the Reporter instance"""
    ADD_CHOICES_INVALID_ARG_TYPE = "ADD_CHOICES_INVALID_ARG_TYPE"
    """Something other than a Choices instance was passed to the Reporter.add_choices() method"""
    ADD_CHOICES_INVALID_CONTENT_TYPE = "ADD_CHOICES_INVALID_CONTENT_TYPE"
    """Something other than a Choice instance was found in the Choices instance passed to the
    Reporter.add_choices() method"""
    INVALID_CHOICES_ARG_TYPE = "INVALID_CHOICES_ARG_TYPE"
    """Something other than a Choices instance was passed as the choices argument to the Reporter constructor"""
    ADD_CHOICE_UNSUPPORTED_SECTION = "ADD_CHOICE_UNSUPPORTED_SECTION"
    """A Section in the Choice instance passed to the Reporter.add_choice() method is not supported by the Reporter"""
    ADD_CHOICE_UNSUPPORTED_TARGET = "ADD_CHOICE_UNSUPPORTED_TARGET"
    """A Target in the Choice instance passed to the Reporter.add_choice() method is not supported by the Reporter"""
    ADD_CHOICE_UNSUPPORTED_FORMAT = "ADD_CHOICE_UNSUPPORTED_FORMAT"
    """A Format in the Choice instance passed to the Reporter.add_choice() method is not supported by the Reporter"""
    ADD_FLAGS_INVALID_PARSER_ARG_TYPE = "ADD_FLAGS_INVALID_PARSER_ARG_TYPE"
    """Something other than an ArgumentParser instance was passed to the Reporter.add_flags_to_argparse() method"""
    ADD_FLAGS_ARGUMENT_ERROR = "ADD_FLAGS_ARGUMENT_ERROR"
    """An ArgumentError was raised when adding flags to the ArgumentParser instance"""
    SELECT_TARGETS_INVALID_ARG_VALUE_TYPE = "SELECT_TARGETS_INVALID_ARG_VALUE_TYPE"
    """The value provided for a target CLI argument has an invalid type"""
    TARGET_FILESYSTEM_INVALID_PATH_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_PATH_ARG_TYPE"
    """Something other than a Path instance was passed to the Reporter._target_filesystem() method"""
    TARGET_FILESYSTEM_PATH_NOT_DIRECTORY = "TARGET_FILESYSTEM_PATH_NOT_DIRECTORY"
    """The Path instance passed to the Reporter._target_filesystem() method is not a directory"""
    TARGET_FILESYSTEM_INVALID_SUBDIR_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_SUBDIR_ARG_TYPE"
    """Something other than a string was passed to the Reporter._target_filesystem() method as the subdir argument"""
    TARGET_FILESYSTEM_EMPTY_SUBDIR_ARG = "TARGET_FILESYSTEM_EMPTY_SUBDIR_ARG"
    """The subdir argument passed to the Reporter.target_filesystem() method cannot be an empty string"""
    TARGET_FILESYSTEM_INVALID_FILENAME_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_FILENAME_ARG_TYPE"
    """Something other than a string was passed to the Reporter._target_filesystem() method as the filename argument"""
    TARGET_FILESYSTEM_EMPTY_FILENAME_ARG = "TARGET_FILESYSTEM_EMPTY_FILENAME_ARG"
    """The filename argument passed to the Reporter.target_filesystem() method cannot be an empty string"""
    TARGET_FILESYSTEM_APPEND_UNIQUE_INCOMPATIBLE_ARGS = (
        "TARGET_FILESYSTEM_APPEND_UNIQUE_INCOMPATIBLE_ARGS")
    """The append and unique options are not compatible when writing to the filesystem"""
    TARGET_FILESYSTEM_OUTPUT_FILE_EXISTS = "TARGET_FILESYSTEM_OUTPUT_FILE_EXISTS"
    """The output file already exists and the append or unique options were not specified"""
    RUN_REPORT_UNSUPPORTED_SECTION = "RUN_REPORT_UNSUPPORTED_SECTION"
    """An unsupported Section was passed to the reporter's run_report() method"""
    RUN_REPORT_INVALID_CHOICE_OPTIONS_TYPE = "RUN_REPORT_INVALID_CHOICE_OPTIONS_TYPE"
    """Something other than a RichTableChoiceOptions instance was set for a choice option"""
    RUN_REPORT_UNSUPPORTED_TARGET = "RUN_REPORT_UNSUPPORTED_TARGET"
    """An unsupported Target was passed to the reporter's run_report() method"""
    UNKNOWN_TARGET_IN_ARGS = "UNKNOWN_TARGET_IN_ARGS"
    """An unknown target string was specified in the command-line arguments"""
    UNSUPPORTED_TARGET_IN_ARGS = "UNSUPPORTED_TARGET_IN_ARGS"
    """An unsupported target string was specified in the command-line arguments"""
