erDiagram
    CoreDataMapping ||--o{ CoreDataTypes : is_a
    CoreDataSequence ||--o{ CoreDataTypes : is_a
    CoreDataSet ||--o{ CoreDataTypes : is_a
    CoreDataPrimitiveTypes ||--o{ CoreDataTypes : is_a
    ImmutableCoreDataTypes ||--o{ CoreDataTypes : is_a

    CoreDataMappingType ||--o{ CoreDataMapping : is_a
    CoreDataSequenceType ||--o{ CoreDataSequence : is_a
    CoreDataSetType ||--o{ CoreDataSet : is_a