"""Tests for the simplebench/si_units.py module."""
# ruff: noqa: F401

import pytest
from testspec import Assert, PytestAction, TestAction, TestSpec

from simplebench import si_units
from simplebench.exceptions import SimpleBenchTypeError, SimpleBenchValueError


@pytest.mark.parametrize("testspec", [
    PytestAction('SI_SCALE_001',
        name="Missing unit arg",
        action=si_units.si_scale, kwargs={'base_unit': 's'},
        exception=TypeError),
    PytestAction('SI_SCALE_002',
        name="Missing base_unit arg",
        action=si_units.si_scale, kwargs={'unit': 's'},
        exception=TypeError),
    PytestAction('SI_SCALE_003',
        name="Invalid unit arg type (int)",
        action=si_units.si_scale, kwargs={'unit': 1, 'base_unit': 's'},
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_INVALID_UNIT_ARG_TYPE),
    PytestAction('SI_SCALE_004',
        name="Invalid base_unit arg type (int)",
        action=si_units.si_scale, kwargs={'unit': 's', 'base_unit': 1},
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_INVALID_BASE_UNIT_ARG_TYPE),
    PytestAction('SI_SCALE_005',
        name="Empty base_unit arg",
        action=si_units.si_scale, kwargs={'unit': 's', 'base_unit': ''},
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_EMPTY_BASE_UNIT_ARG),
    PytestAction('SI_SCALE_006',
        name="unit does not end with base_unit",
        action=si_units.si_scale, kwargs={'unit': 'ms', 'base_unit': 'm'},
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_UNIT_DOES_NOT_END_WITH_BASE_UNIT),
    PytestAction('SI_SCALE_007',
        name="Unknown prefix in unit",
        action=si_units.si_scale, kwargs={'unit': 'xs', 'base_unit': 's'},
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_UNKNOWN_SI_UNIT_PREFIX),
    PytestAction('SI_SCALE_008',
        name="Valid unit 's'",
        action=si_units.si_scale, args=['s', 's'],
        expected=1.0),
    PytestAction('SI_SCALE_009',
        name="Valid unit 'Ts'",
        action=si_units.si_scale, args=['Ts', 's'],
        expected=1e12),
    PytestAction('SI_SCALE_010',
        name="Valid unit 'Gs'",
        action=si_units.si_scale, args=['Gs', 's'],
        expected=1e9),
    PytestAction('SI_SCALE_011',
        name="Valid unit 'Ms'",
        action=si_units.si_scale, args=['Ms', 's'],
        expected=1e6),
    PytestAction('SI_SCALE_012',
        name="Valid unit 'ks'",
        action=si_units.si_scale, args=['ks', 's'],
        expected=1e3),
    PytestAction('SI_SCALE_013',
        name="Valid unit ''",
        action=si_units.si_scale, args=['s', 's'],
        expected=1.0),
    PytestAction('SI_SCALE_014',
        name="Valid unit 'ms'",
        action=si_units.si_scale, args=['ms', 's'],
        expected=1e-3),
    PytestAction('SI_SCALE_015',
        name="Valid unit 'μs'",
        action=si_units.si_scale,
        args=['μs', 's'],  # '\u03bc' Greek Small Letter Mu (SI standard)
        expected=1e-6),
    PytestAction('SI_SCALE_016',
        name="Valid unit 'µs'",
        action=si_units.si_scale,
        args=['µs', 's'],  # '\u00b5' Micro Sign (legacy Unicode compatibility)
        expected=1e-6),
    PytestAction('SI_SCALE_017',
        name="Valid unit 'ns'",
        action=si_units.si_scale, args=['ns', 's'],
        expected=1e-9),
    PytestAction('SI_SCALE_018',
        name="Valid unit 'ps'",
        action=si_units.si_scale, args=['ps', 's'],
        expected=1e-12),
])
def test_si_scale(testspec: TestAction) -> None:
    """Test si_units.si_scale() function.

    :param testspec: The test specification to run.
    :type testspec: TestAction
    """
    testspec.run()


@pytest.mark.parametrize("testspec", [
    PytestAction('SI_SCALE_TO_UNIT_001',
        name="missing base_unit arg",
        action=si_units.si_scale_to_unit,
        kwargs={'current_unit': 's', 'target_unit': 's'},
        exception=TypeError),
    PytestAction('SI_SCALE_TO_UNIT_002',
        name="missing current_unit arg",
        action=si_units.si_scale_to_unit,
        kwargs={'base_unit': 's', 'target_unit': 's'},
        exception=TypeError),
    PytestAction('SI_SCALE_TO_UNIT_003',
        name="missing target_unit arg",
        action=si_units.si_scale_to_unit,
        kwargs={'base_unit': 's', 'current_unit': 's'},
        exception=TypeError),
    PytestAction('SI_SCALE_TO_UNIT_004',
        name="invalid base_unit arg type (int)",
        action=si_units.si_scale_to_unit,
        kwargs={'base_unit': 1, 'current_unit': 's', 'target_unit': 's'},
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_INVALID_BASE_UNIT_ARG_TYPE),
    PytestAction('SI_SCALE_TO_UNIT_005',
        name="invalid current_unit arg type (int)",
        kwargs={'base_unit': 's', 'current_unit': 1, 'target_unit': 's'},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_INVALID_CURRENT_UNIT_ARG_TYPE),
    PytestAction('SI_SCALE_TO_UNIT_006',
        name="invalid target_unit arg type (int)",
        kwargs={'base_unit': 's', 'current_unit': 's', 'target_unit': 1},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_INVALID_TARGET_UNIT_ARG_TYPE),
    PytestAction('SI_SCALE_TO_UNIT_007',
        name="empty base_unit arg",
        kwargs={'base_unit': '', 'current_unit': 's', 'target_unit': 's'},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_EMPTY_BASE_UNIT_ARG),
    PytestAction('SI_SCALE_TO_UNIT_008',
        name="empty current_unit arg",
        kwargs={'base_unit': 's', 'current_unit': '', 'target_unit': 's'},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_EMPTY_CURRENT_UNIT_ARG),
    PytestAction('SI_SCALE_TO_UNIT_009',
        name="empty target_unit arg",
        kwargs={'base_unit': 's', 'current_unit': 's', 'target_unit': ''},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_EMPTY_TARGET_UNIT_ARG),
    PytestAction('SI_SCALE_TO_UNIT_010',
        name="base_unit does not match other units",
        kwargs={'base_unit': 'm', 'current_unit': 'ms', 'target_unit': 'ms'},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_INCOMPATIBLE_UNITS),
    PytestAction('SI_SCALE_TO_UNIT_011',
        name="current_unit does not match other units",
        kwargs={'base_unit': 'ms', 'current_unit': 'm', 'target_unit': 'ms'},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_INCOMPATIBLE_UNITS),
    PytestAction('SI_SCALE_TO_UNIT_012',
        name="target_unit does not match other units",
        kwargs={'base_unit': 'ms', 'current_unit': 'ms', 'target_unit': 'm'},
        action=si_units.si_scale_to_unit,
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_TO_UNIT_INCOMPATIBLE_UNITS),
    PytestAction('SI_SCALE_TO_UNIT_013',
        name="valid args, no scaling (s to s)",
        args=['s', 's', 's'],
        action=si_units.si_scale_to_unit,
        expected=1.0),
    PytestAction('SI_SCALE_TO_UNIT_014',
        name="valid args, scaling up (ms to s)",
        args=['s', 'ms', 's'],
        action=si_units.si_scale_to_unit,
        expected=1e3),
    PytestAction('SI_SCALE_TO_UNIT_015',
        name="valid args, scaling down (s to ms)",
        args=['s', 's', 'ms'],
        action=si_units.si_scale_to_unit,
        expected=1e-3),
])
def test_si_scale_to_unit(testspec: TestAction) -> None:
    """Test si_units.si_scale_to_unit() function.

    :param testspec: The test specification to run.
    :type testspec: TestAction
    """
    testspec.run()


@pytest.mark.parametrize("testspec", [
    PytestAction('SI_UNIT_BASE_001',
        name="Missing unit arg",
        action=si_units.si_unit_base,
        exception=TypeError),
    PytestAction('SI_UNIT_BASE_002',
        name="Invalid unit arg type (int)",
        args=[1],
        action=si_units.si_unit_base,
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_UNIT_BASE_INVALID_UNIT_ARG_TYPE),
    PytestAction('SI_UNIT_BASE_003',
        name="Empty unit arg",
        args=[''],
        action=si_units.si_unit_base,
        exception=SimpleBenchValueError,
        exception_tag=si_units._SIUnitsErrorTag.SI_UNIT_BASE_EMPTY_UNIT_ARG),
    PytestAction('SI_UNIT_BASE_004',
        name="No known prefix in unit",
        args=['xs'],
        action=si_units.si_unit_base,
        expected='xs'),
])
def test_si_unit_base(testspec: TestAction) -> None:
    """Test si_units.si_unit_base() function.

    :param testspec: The test specification to run.
    :type testspec: TestAction
    """
    testspec.run()


@pytest.mark.parametrize("testspec", [
    PytestAction('SI_SCALE_FOR_SMALLEST_001',
        name="Missing arguments",
        kwargs={},
        action=si_units.si_scale_for_smallest,
        exception=TypeError),
    PytestAction('SI_SCALE_FOR_SMALLEST_002',
        name="Invalid numbers arg type (int)",
        kwargs={'numbers': 1, 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_FOR_SMALLEST_INVALID_NUMBERS_ARG_TYPE),
    PytestAction('SI_SCALE_FOR_SMALLEST_003',
        name="Invalid numbers arg type (str)",
        kwargs={'numbers': 'not_a_list_of_numbers', 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_FOR_SMALLEST_INVALID_NUMBERS_ARG_TYPE),
    PytestAction('SI_SCALE_FOR_SMALLEST_004',
        name="Invalid numbers arg type (bytes)",
        kwargs={'numbers': b'not_a_list_of_numbers', 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_FOR_SMALLEST_INVALID_NUMBERS_ARG_TYPE),
    PytestAction('SI_SCALE_FOR_SMALLEST_005',
        name="Invalid numbers arg value type (list with str)",
        kwargs={'numbers': [1, 2, 'not_a_number'], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        exception=SimpleBenchTypeError,
        exception_tag=si_units._SIUnitsErrorTag.SI_SCALE_FOR_SMALLEST_INVALID_NUMBERS_ARG_VALUES_TYPE),
    PytestAction('SI_SCALE_FOR_SMALLEST_006',
        name="Empty numbers list",
        kwargs={'numbers': [], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('s', 1.0)),
    PytestAction('SI_SCALE_FOR_SMALLEST_007',
        name="List with one number",
        kwargs={'numbers': [0.01234], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('ms', 1e3)),
    PytestAction('SI_SCALE_FOR_SMALLEST_008',
        name="List with multiple numbers",
        kwargs={'numbers': [0.01234, 0.0005678, 0.000009], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('μs', 1e6)),
    PytestAction('SI_SCALE_FOR_SMALLEST_009',
        name="List with zero and positive numbers",
        kwargs={'numbers': [0.0, 0.01234, 0.0005678, 0.000009], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('μs', 1e6)),
    PytestAction('SI_SCALE_FOR_SMALLEST_010',
        name="List with negative and positive numbers",
        kwargs={'numbers': [-0.01234, 0.0005678, -0.000009], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('μs', 1e6)),
    PytestAction('SI_SCALE_FOR_SMALLEST_011',
        name="List with all zeros",
        kwargs={'numbers': [0.0, 0.0, 0.0], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('s', 1.0)),
    PytestAction('SI_SCALE_FOR_SMALLEST_012',
        name="List with all zeros and negative zeros",
        kwargs={'numbers': [0.0, -0.0, 0.0], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('s', 1.0)),
    PytestAction('SI_SCALE_FOR_SMALLEST_013',
        name="List with very large and very small numbers",
        kwargs={'numbers': [1e12, 1e-12, 1e6, 1e-6], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('ps', 1e12)),
    PytestAction('SI_SCALE_FOR_SMALLEST_014',
        name="List with one very large number",
        kwargs={'numbers': [1e12], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('Ts', 1e-12)),
    PytestAction('SI_SCALE_FOR_SMALLEST_015',
        name="List with one very small number",
        kwargs={'numbers': [1e-12], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('ps', 1e12)),
    PytestAction('SI_SCALE_FOR_SMALLEST_016',
        name="List with mixed int and float numbers",
        kwargs={'numbers': [1234, 0.5678, -9], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('ms', 1e3)),
    PytestAction('SI_SCALE_FOR_SMALLEST_017',
        name="List with EXTREMELY small numbers",
        kwargs={'numbers': [1e-30, 1e-25, 1e-32], 'base_unit': 's'},
        action=si_units.si_scale_for_smallest,
        expected=('ps', 1e12)),
])
def test_si_scale_for_smallest(testspec: TestAction) -> None:
    """Test si_units.si_scale_for_smallest() function.

    :param testspec: The test specification to run.
    :type testspec: TestAction
    """
    testspec.run()
