"""ErrorTags for ChoiceConf class"""
from simplebench.enums import enum_docstrings
from simplebench.exceptions import ErrorTag


@enum_docstrings
class _ChoiceConfErrorTag(ErrorTag):
    """ErrorTags for ChoiceConf class."""
    FLAG_TYPE_INVALID_ARG_TYPE = "FLAG_TYPE_INVALID_ARG_TYPE"
    """The flag_type argument is not a FlagType enum value."""
    FLAGS_INVALID_ARG_TYPE = "FLAGS_INVALID_ARG_TYPE"
    """The flags argument is not a Sequence of strings."""
    FLAGS_INVALID_ARGS_VALUE = "FLAGS_INVALID_ARGS_VALUE"
    """One or more items in the flags argument is an empty string,
    blank string, or whitespace-only string."""
    NAME_INVALID_ARG_TYPE = "NAME_INVALID_ARG_TYPE"
    """The name argument is not a string."""
    NAME_INVALID_ARG_VALUE = "NAME_INVALID_ARG_VALUE"
    """The name argument is an empty string or blank string."""
    DESCRIPTION_INVALID_ARG_TYPE = "DESCRIPTION_INVALID_ARG_TYPE"
    """The description argument is not a string."""
    DESCRIPTION_INVALID_ARG_VALUE = "DESCRIPTION_INVALID_ARG_VALUE"
    """The description argument is an empty string or blank string."""
    SECTIONS_INVALID_ARG_TYPE = "SECTIONS_INVALID_ARG_TYPE"
    """The sections argument is not a Sequence of Section enum values."""
    SECTIONS_INVALID_ARG_VALUE = "SECTIONS_INVALID_ARG_VALUE"
    """One or more items in the sections argument is not a Section enum value,
    or the sections argument is an empty sequence."""
    TARGETS_INVALID_ARG_TYPE = "TARGETS_INVALID_ARG_TYPE"
    """The targets argument is not a Sequence of Target enum values."""
    TARGETS_INVALID_ARG_VALUE = "TARGETS_INVALID_ARG_VALUE"
    """One or more items in the targets argument is not a Target enum value,
    or the targets argument is an empty sequence."""
    DEFAULT_TARGETS_INVALID_ARG_TYPE = "DEFAULT_TARGETS_INVALID_ARG_TYPE"
    """The default_targets argument is not a Sequence of Target enum values."""
    DEFAULT_TARGETS_INVALID_ARG_VALUE = "DEFAULT_TARGETS_INVALID_ARG_VALUE"
    """One or more items in the default_targets argument is not a Target enum value."""
    SUBDIR_INVALID_ARG_TYPE = "SUBDIR_INVALID_ARG_TYPE"
    """The subdir argument is not a string."""
    SUBDIR_INVALID_ARG_VALUE = "SUBDIR_INVALID_ARG_VALUE"
    """The subdir argument is not alphanumeric or is a blank string."""
    SUBDIR_TOO_LONG = "SUBDIR_TOO_LONG"
    """The subdir argument is longer than 64 characters."""
    FILE_SUFFIX_INVALID_ARG_TYPE = "FILE_SUFFIX_INVALID_ARG_TYPE"
    """The file_suffix argument is not a string."""
    FILE_SUFFIX_INVALID_ARG_VALUE = "FILE_SUFFIX_INVALID_ARG_VALUE"
    """The file_suffix argument is a blank string, contains non-alphanumeric characters,
    or is longer than 10 characters."""
    FILE_SUFFIX_TOO_LONG = "FILE_SUFFIX_TOO_LONG"
    """The file_suffix argument is longer than 10 characters."""
    FILE_UNIQUE_INVALID_ARG_TYPE = "FILE_UNIQUE_INVALID_ARG_TYPE"
    """The file_unique argument is not a boolean value or None."""
    FILE_APPEND_INVALID_ARG_TYPE = "FILE_APPEND_INVALID_ARG_TYPE"
    """The file_append argument is not a boolean value or None."""
    FILE_UNIQUE_FILE_APPEND_MUTUALLY_EXCLUSIVE = "FILE_UNIQUE_FILE_APPEND_MUTUALLY_EXCLUSIVE"
    """The file_unique and file_append arguments cannot both be set to True or both be set to False."""
    OUTPUT_FORMAT_INVALID_ARG_TYPE = "OUTPUT_FORMAT_INVALID_ARG_TYPE"
    """The output_format argument is not a Format enum value."""
    OPTIONS_INVALID_ARG_TYPE = "OPTIONS_INVALID_ARG_TYPE"
    """The options argument is not a ReporterOptions instance."""
    OPTIONS_INVALID_ARG_VALUE = "OPTIONS_INVALID_ARG_VALUE"
    """One or more items in the options argument is not a ReporterOptions instance."""
