"""ErrorTags for the session module."""
from ..enums import enum_docstrings
from .base import ErrorTag


@enum_docstrings
class _SessionErrorTag(ErrorTag):
    """ErrorTags for the session module."""
    PROPERTY_INVALID_TIMER_ARG = "PROPERTY_INVALID_TIMER_ARG"
    """Something other than a callable was assigned to the timer property"""
    PROPERTY_INVALID_TIMER_RETURN_TYPE = "PROPERTY_INVALID_TIMER_RETURN_TYPE"
    """The callable assigned to the timer property did not return an int"""
    INVALID_CASES_SEQUENCE_ARG = "INVALID_CASES_SEQUENCE_ARG"
    """Something other than a Sequence of Case instances was passed to the Session() constructor"""
    INIT_INVALID_CASE_ARG_IN_SEQUENCE = "INIT_INVALID_CASE_ARG_IN_SEQUENCE"
    """Something other than a Case instance was found in the Sequence passed to the Session() constructor"""
    INIT_INVALID_VERBOSITY_ARG = "INIT_INVALID_VERBOSITY_ARG"
    """Something other than a Verbosity instance was passed to the Session() constructor"""
    INIT_INVALID_OUTPUT_PATH_ARG = "INIT_INVALID_OUTPUT_PATH_ARG"
    """Something other than a Path instance was passed to the Session() constructor as the path arg"""
    PROPERTY_INVALID_CASES_ARG = "PROPERTY_INVALID_CASES_ARG"
    """Something other than a Sequence of Case instances was passed to the cases property"""
    PROPERTY_INVALID_CASE_ARG_IN_SEQUENCE = "PROPERTY_INVALID_CASE_ARG_IN_SEQUENCE"
    """Something other than a Case instance was found in the Sequence passed to the cases property"""
    PROPERTY_INVALID_VERBOSITY_ARG = "PROPERTY_INVALID_VERBOSITY_ARG"
    """Something other than a Verbosity instance was passed to the verbosity property"""
    PROPERTY_INVALID_CASE_ARG = "PROPERTY_INVALID_CASE_ARG"
    """Something other than a Case instance was found in the Sequence passed to the cases property"""
    PROPERTY_INVALID_PROGRESS_ARG = "PROPERTY_INVALID_PROGRESS_ARG"
    """Something other than a bool was passed to the progress property"""
    PROPERTY_INVALID_OUTPUT_PATH_ARG = "PROPERTY_INVALID_OUTPUT_PATH_ARG"
    """Something other than a Path instance was passed to the output_path property"""
    RUN_NO_CASES_TO_RUN = "RUN_NO_CASES_TO_RUN"
    """No benchmark cases were found to run"""
    REPORT_INVALID_CHOICE_RETRIEVED = "REPORT_INVALID_CHOICE_RETRIEVED"
    """Something other than a Choice instance was retrieved from the report"""
    REPORT_OUTPUT_PATH_NOT_SET = "REPORT_OUTPUT_PATH_NOT_SET"
    """The output path must be set to generate reports"""
    PARSE_ARGS_INVALID_ARGSPARSER_ARG = "PARSE_ARGS_INVALID_ARGSPARSER_ARG"
    """Something other than an ArgumentParser instance was passed to the Session.parse_args() method"""
    PROPERTY_INVALID_ARGSPARSER_ARG = "PROPERTY_INVALID_ARGSPARSER_ARG"
    """Something other than an ArgumentParser instance was assigned to the args_parser property"""
    PROPERTY_INVALID_ARGS_ARG = "PROPERTY_INVALID_ARGS_ARG"
    """Something other than a Namespace instance was found in the args property"""
    PROPERTY_INVALID_DEFAULT_RUNNER_ARG = "PROPERTY_INVALID_DEFAULT_RUNNER_ARG"
    """Something other than a subclass of SimpleRunner or None was assigned to the default_runner property"""
    PROPERTY_INVALID_CONSOLE_ARG = "PROPERTY_INVALID_CONSOLE_ARG"
    """Something other than a Console instance was assigned to the console property"""
    PARSE_ARGS_INVALID_ARGS_TYPE = "PARSE_ARGS_INVALID_ARGS_TYPE"
    """Something other than a list of strings was passed to the Session.parse_args() method as the args argument"""
    PARSE_ARGS_INVALID_ARGS_ITEM_TYPE = "PARSE_ARGS_INVALID_ARGS_ITEM_TYPE"
    """Something other than a string was found in the list passed to the Session.parse_args()
    method as the args argument"""
    ARGUMENT_ERROR_ADDING_FLAGS = "ARGUMENT_ERROR_ADDING_FLAGS"
    """An error occurred while adding flags to the ArgumentParser instance"""
