"""Builder exception ErrorTags for JSON report objects."""
from simplebench.enums import enum_docstrings
from simplebench.exceptions import ErrorTag


@enum_docstrings
class _HydratorErrorTag(ErrorTag):
    """Builder exception ErrorTags for JSON report objects."""
    INVALID_PROCESS_AS_TYPE = "INVALID_PROCESS_AS_TYPE"
    "Invalid `process_as` type. Must be a `dict`."
    INVALID_PROCESS_AS_KEY = "INVALID_PROCESS_AS_KEY"
    "Invalid `process_as` key. Not listed in `allowed` keys."
    INVALID_PROCESS_AS_NOT_CALLABLE = "INVALID_PROCESS_AS_NOT_CALLABLE"
    "Invalid `process_as` value. Not callable."
    INVALID_PROCESS_AS_TOO_MANY_PARAMETERS = "INVALID_PROCESS_AS_TOO_MANY_PARAMETERS"
    "Invalid `process_as` value. Cannot have more than one parameter."
    INVALID_PROCESS_AS_NOT_POSITIONAL = "INVALID_PROCESS_AS_NOT_POSITIONAL"
    "Invalid `process_as` value. Must take positional-only or positional-or-keyword parameters."
    INVALID_PROCESS_AS_NO_RETURN_ANNOTATION = "INVALID_PROCESS_AS_NO_RETURN_ANNOTATION"
    "Invalid `process_as` value. Must have a return type annotation."
    INVALID_MATCH_ON_TYPE = "INVALID_MATCH_ON_TYPE"
    "Invalid `match_on` type. Must be a `dict`."
    INVALID_MATCH_ON_KEY = "INVALID_MATCH_ON_KEY"
    "Invalid `match_on` key. Not listed in `allowed` keys."
    INVALID_DEFAULT_TYPE = "INVALID_DEFAULT_TYPE"
    "Invalid `default` value type. Must be a `dict`."
    INVALID_DEFAULT_KEY = "INVALID_DEFAULT_KEY"
    "Invalid `default` key. Not listed in `optional` keys."
    INVALID_DATA_VALUE_TYPE = "INVALID_DATA_VALUE_TYPE"
    "Invalid `data` value type. Did not match the `allowed` type."
    INVALID_DATA_KEY = "INVALID_DATA_KEY"
    "Invalid `data` key. Not listed in `allowed` keys."
    INVALID_MATCH_ON_VALUE = "INVALID_MATCH_ON_VALUE"
    "Invalid `match_on` value. Not listed in `allowed` keys."
    INVALID_ALLOWED_EMPTY = "INVALID_ALLOWED_EMPTY"
    "Invalid `allowed` value. The dictionary cannot be empty."
    INVALID_SKIP_VALUE = "INVALID_SKIP_VALUE"
    "Invalid `skip` value. Not listed in `allowed` keys."
    INVALID_ALLOWED_VALUE_TYPE = "INVALID_ALLOWED_VALUE_TYPE"
    "Invalid `allowed` value. Expected a `type`."
    INVALID_SKIP_TYPE = "INVALID_SKIP_TYPE"
    "Invalid `skip` type: Must be an Iterable of str."
    INVALID_SKIP_ITEM_TYPE = "INVALID_SKIP_ITEM_TYPE"
    "Invalid type for an item in the `skip` parameter. Expected `str`."
    INVALID_ALLOWED_TYPE = "INVALID_ALLOWED_TYPES_TYPE"
    "Invalid `allowed` type: Must be a dict."
    INVALID_OPTIONAL_TYPE = "INVALID_OPTIONAL_TYPE_TYPE"
    "Invalid `optional` type: Must be an Iterable of str."
    INVALID_OPTIONAL_ITEM_TYPE = "INVALID_OPTIONAL_ITEM_TYPE"
    "Invalid type for an item in the `optional` parameter. Expected `str`."
    INVALID_OPTIONAL_ITEM_VALUE = "INVALID_OPTIONAL_ITEM_VALUE"
    "Invalid value for an item in the `optional` parameter. Not listed in `allowed` keys."
    INVALID_ERROR_TAG_TYPE = "INVALID_ERROR_TAG_TYPE"
    "Invalid type for the `error_tag` parameter. Expected type `ErrorTag`."
    INVALID_DATA_TYPE = "INVALID_DATA_TYPE"
    "Invalid type for the `data` parameter. Expected type `dict`."
    INVALID_DATA_KEY_TYPE = "INVALID_DATA_KEY_TYPE"
    "Invalid key type in the `data` parameter. Expected type `str`."
    INVALID_OPTIONAL_FIELDS_TYPE = "INVALID_OPTIONAL_FIELDS_TYPE"
    "Invalid type for the `optional_fields` parameter. Expected Iterable of `str`."
    INVALID_OPTIONAL_FIELDS_ITEM_TYPE = "INVALID_OPTIONAL_FIELDS_ITEM_TYPE"
    "Invalid type for an item in the `optional_fields` parameter. Expected `str`."
