"""ErrorTags for simplebench.reporters.choices"""
from simplebench.exceptions.base import ErrorTag
from simplebench.enums import enum_docstrings


@enum_docstrings
class ChoicesErrorTag(ErrorTag):
    """ErrorTags for simplebench.reporters.choices."""
    INVALID_CHOICES_ARG_TYPE = "INVALID_CHOICES_ARG_TYPE"
    """Something other than a Sequence of Choice instances or a Choices instance was passed as the choices arg"""
    INVALID_CHOICES_ARG_SEQUENCE_TYPE = "INVALID_CHOICES_ARG_SEQUENCE_TYPE"
    """Something other than a Sequence was passed as the choices arg"""
    INVALID_CHOICES_ITEM_VALUE = "INVALID_CHOICES_ITEM_VALUE"
    """Something other than a Choice instance was found in the Sequence passed as the choices arg"""
    ADD_INVALID_CHOICE_ARG_TYPE = "ADD_INVALID_CHOICE_ARG_TYPE"
    """Something other than a Choice instance was passed to the Choices.add() method"""
    ADD_DUPLICATE_CHOICE_NAME = "ADD_DUPLICATE_CHOICE_NAME"
    """A Choice with the same name already exists in the Choices instance"""
    ADD_DUPLICATE_CLI_ARG = "ADD_DUPLICATE_CLI_ARG"
    """A Choice with the same CLI argument already exists in the Choices instance"""
    EXTEND_INVALID_CHOICES_ARG_SEQUENCE_TYPE = "EXTEND_INVALID_CHOICES_ARG_SEQUENCE_TYPE"
    """Something other than a Sequence was passed to the Choices.extend() method"""
    EXTEND_INVALID_CHOICES_ITEM_VALUE = "EXTEND_INVALID_CHOICES_ITEM_VALUE"
    """Something other than a Choice instance was found in the Sequence passed to the Choices.extend() method"""
    EXTEND_DUPLICATE_CHOICE_NAME = "EXTEND_DUPLICATE_CHOICE_NAME"
    """A Choice with the same name already exists in the Choices instance"""
    EXTEND_DUPLICATE_CLI_ARG = "EXTEND_DUPLICATE_CLI_ARG"
    """A Choice with the same CLI argument already exists in the Choices instance"""
    GET_CHOICE_FOR_ARG_INVALID_ARG_TYPE = "GET_CHOICE_FOR_ARG_INVALID_ARG_TYPE"
    """Something other than a string was passed to the Choices.get_choice_for_arg() method"""
    GET_CHOICE_FOR_ARG_INVALID_ARG_VALUE = "GET_CHOICE_FOR_ARG_INVALID_ARG_VALUE"
    """No Choice with the given CLI argument exists in the Choices instance"""
    CHOICE_FOR_FLAG_INVALID_ARG = "CHOICE_FOR_FLAG_INVALID_ARG"
    """Something other than a string was passed to the Choices.choice_for_flag() method"""
    GET_CHOICE_BY_CLI_TAG_INVALID_ARG = "GET_CHOICE_BY_CLI_TAG_INVALID_ARG"
    """Something other than a string was passed to the Choices.get_choice_by_cli_tag() method"""
    ALL_CHOICE_FLAGS_INVALID_RETURN = "ALL_CHOICE_FLAGS_INVALID_RETURN"
    """Something other than a set of strings was returned from the Choices.all_choice_flags() method"""
    DELITEM_UNKNOWN_CHOICE_NAME = "DELITEM_UNKNOWN_CHOICE_NAME"
    """No Choice with the given name exists in the Choices instance"""
    ADD_DUPLICATE_CHOICE_FLAG = "ADD_DUPLICATE_CHOICE_FLAG"
    """A Choice with the same CLI argument already exists in the Choices instance"""
    SETITEM_INVALID_VALUE_TYPE = "SETITEM_INVALID_VALUE_TYPE"
    """Something other than a Choice instance was passed as the value to the Choices.__setitem__() method"""
    SETITEM_INVALID_KEY_TYPE = "SETITEM_INVALID_KEY_TYPE"
    """Something other than a string was passed as the key to the Choices.__setitem__() method"""
    SETITEM_KEY_NAME_MISMATCH = "SETITEM_KEY_NAME_MISMATCH"
    """The key passed to the Choices.__setitem__() method does not match the name attribute of the Choice instance"""
    SETITEM_DUPLICATE_CHOICE_NAME = "SETITEM_DUPLICATE_CHOICE_NAME"
    """A Choice with the same name already exists in the Choices instance"""
    SETITEM_DUPLICATE_CHOICE_FLAG = "SETITEM_DUPLICATE_CHOICE_FLAG"
    """A Choice with the same CLI argument flag already exists in the Choices instance"""
