"""CPUInfo version 1 class.

The CPUInfo class represents a version 1 JSON CPUInfo.

It provides methods to convert to and from dictionary representations
and includes schema validation specific to version 1 reports.

The version 1 CPUInfo is the first stable version of the JSON CPUInfo format
and serves as a foundation for future versions.

As the foundational version, this class is considered immutable. Future versions
will inherit from this class to extend its functionality, but this implementation
will not be changed.
"""
import hashlib
import json
from types import MappingProxyType
from typing import cast

from simplebench.report._base.cpu_info import BaseCPUInfo
from simplebench.report._base.json_schema import JSONSchema
from simplebench.types import CoreDataMappingType, ImmutableCoreDataMappingType

from ..types import CPUInfoData, ImmutableCPUInfoData, ImmutableCPUInfoDict
from . import _validate
from ._cpu_info_schema import CPUInfoSchema


class CPUInfo(BaseCPUInfo):
    """Class representing a JSON CPUInfo version 1."""

    TYPE: str = CPUInfoSchema.TYPE
    """The JSON CPUInfo type property value for version 1 reports."""

    VERSION: int = CPUInfoSchema.VERSION
    """The JSON CPUInfo version number."""

    SCHEMA: type[JSONSchema] = CPUInfoSchema
    """The JSON schema class for version 1 reports."""


    def __init__(self,
                 *,
                 hash_id: str | None = None,
                 data: CoreDataMappingType) -> None:
        """Initialize CPUInfo.

        :param str | None hash_id: The unique hash identifier for the CPU information.
            If not provided it will be computed automatically.

            The hash_id must be a 64 character hexadecimal string, an
            empty string, or None.

            The semantics of hash_id are NOT to provide integrity verification of the data,
            but rather to provide a globally unique identifier for the specific CPU information
            for this instance. It can be used to compare CPU information across different systems
            or runs to determine if they represent the same CPU configuration as long
            as the data was generated by the same version of the CPUInfo reporter.

            In other words, two CPUInfo instances with the same hash_id can be assumed to represent
            the same CPU information if they were generated by the same version of the reporter.

            Because the hash_id is derived from the data content, any change to the data
            will result in a different hash_id. This means that the hash_id can be used
            to quickly check if two CPUInfo instances are identical in terms of their
            CPU information and originating source.

            It is recommended to let the hash_id be computed automatically to ensure
            consistency and correctness unless importing data from an external source.
            
            hash_id values are NOT validated against the data content on initialization
            because it is only an opaque identifier, not a data validation mechanism.

        :param CoreDataMappingType data: The raw CPU information data collected from the system
            using the :package:`cpuinfo` library. It must either be a dictionary or
            an instance of `simplebench.environment.CPUInfo`.

            The dictionary must conform to the following rules:
            - It can have arbitrary keys and values but must be a tree composed of
              dictionaries, lists, strings, numbers, booleans, and nulls.
            - All keys in dictionaries must be non-blank, non-empty strings.
        """
        self._data: ImmutableCPUInfoData = _validate.data(data)
        self._hash_id: str | None = _validate.hash_id(hash_id, allow_none=True)
        self._to_dict_cache: ImmutableCPUInfoDict | None = None

    @property
    def hash_id(self) -> str:
        """Get the hash_id property.

        We can't use the helper from the base class because we need to
        compute the hash_id based on the data property which is a complex structure
        of dictionaries and lists. So we serialize the data to a sorted JSON string
        and compute the SHA256 hash of that string.

        :return str | None: The hash_id string or None if not set.
        """
        if self._hash_id is None:
            serialized = json.dumps(self.data, sort_keys=True, separators=(',', ':'))
            self._hash_id = hashlib.sha256(serialized.encode('utf-8')).hexdigest()
        return self._hash_id

    @property
    def data(self) -> ImmutableCPUInfoData:
        """Get the data property.

        :return ImmutableCoreDataMappingType: An immutable mapping of the CPU information data.
        """
        return self._data

    @classmethod
    def from_dict(cls, data: CPUInfoData) -> 'CPUInfo':
        """Create a CPUInfo instance from a dictionary.

        .. code-block:: python
           :caption: Example

           cpu_info = CPUInfo.from_dict(data)

        The dictionary must conform to the expected structure for the CPUInfo
        representation. The 'version' and 'type' properties are validated
        against the class's VERSION and TYPE attributes if they are present.

        :param CPUInfoDict data: The dictionary containing CPU information.
        :return CPUInfo: A CPUInfo instance.
        """
        allowed_keys = cls.init_params()
        allowed_keys['version'] = int
        allowed_keys['type'] = str

        kwargs = cls.import_data(
            data=data,
            allowed_fields=allowed_keys,
            skip_fields={'version', 'type'},
            optional_fields={'hash_id', 'version', 'type'},
            defaults={'hash_id': None, 'version': cls.VERSION, 'type': cls.TYPE},
            match_on={'version': cls.VERSION, 'type': cls.TYPE})
        return cls(**kwargs)

    def to_dict(self) -> ImmutableCPUInfoDict:
        """Returns the CPUInfo as an immutable dictionary suitable for JSON serialization.

        This includes all properties defined in the :class:`CPUInfoSchema`
        for the version 1 CPUInfo.

        :return ImmutableCPUInfoDict: An immutable mapping representation of the CPUInfo.
        """
        if self._to_dict_cache is None:
            cls = self.__class__
            self._to_dict_cache = cast(ImmutableCPUInfoDict,
                MappingProxyType({
                'type': cls.TYPE,
                'version': cls.VERSION,
                'hash_id': self.hash_id,
                'data': cast(ImmutableCoreDataMappingType, self.data)
            }))
        return self._to_dict_cache
