"""V1 ExecutionEnvironment implementation."""

import hashlib
from collections.abc import Iterator, Mapping
from types import MappingProxyType
from typing import cast

from simplebench.exceptions import SimpleBenchTypeError
from simplebench.report._error_tags import _ExecutionEnvironmentErrorTag
from simplebench.report.base import BaseExecutionEnvironment, Environment
from simplebench.report.versions.v1.python_info import PythonInfo
from simplebench.simplebench_types import CoreDataMappingType
from simplebench.validators import validate_core_data_mapping

from . import _validate
from .known_environments import KNOWN_ENVIRONMENTS
from .typeddict_types import ExecutionEnvironmentDict

__all__: list[str] = []


class ExecutionEnvironment(BaseExecutionEnvironment, Mapping[str, Environment]):
    """Implementation of the ExecutionEnvironment interface for V1."""

    def __init__(self, **kwargs: CoreDataMappingType | Environment) -> None:
        """Initialize the ExecutionEnvironment with environment information.

        In the V1 implementation, the python parameter is the only pre-defined
        environment and must be of type PythonInfo. Additional environments can be
        provided as keyword arguments and must conform to the CoreDataMappingType.

        At least one environment must be provided.

        :param PythonInfo python: (optional) The Python info.
        :param CoreDataMappingType | Environment kwargs: (optional) Other execution
            environments as keyword arguments.
        :raises SimpleBenchTypeError: If a passed environment is of an incorrect type.
        """
        self._environments: MappingProxyType[str, Environment] = _validate.environments(dict(kwargs))
        self._hash_id: str = self._compute_hash_id()

    def _compute_hash_id(self) -> str:
        """Compute the hash ID for the execution environments.

        The hash ID is generated by concatenating the keys and hash IDs of each individual
        environment in sorted order by environment name, separated by pipe characters,
        and then hashing the result.

        :return: A 64-character hexadecimal hash ID string.
        """
        hash_parts = []
        for env_name in sorted(self._environments.keys()):
            env = self._environments[env_name]
            hash_parts.append(f'{env_name}={env.hash_id}')
        hash_tuple: tuple[str, ...] = tuple(hash_parts)
        return hashlib.sha256('|'.join(hash_tuple).encode('utf-8')).hexdigest()

    @classmethod
    def from_dict(cls, data: Mapping[str, CoreDataMappingType]) -> 'ExecutionEnvironment':
        """Create an ExecutionEnvironment instance from a dictionary.

        .. code-block:: python
           :caption: Example

           environment_info = ExecutionEnvironment.from_dict(data)

        :param data: The dictionary containing execution environment information.
        :return: A ExecutionEnvironment instance.
        """
        imported_environments: dict[str, CoreDataMappingType | Environment] = {}
        for env_name, env_value in data.items():
            if env_name in KNOWN_ENVIRONMENTS:
                environment: type[Environment] = KNOWN_ENVIRONMENTS[env_name]
                imported_instance = environment.from_dict(env_value)
                imported_environments[env_name] = imported_instance
            else:
                imported_environments[env_name] = validate_core_data_mapping(
                    env_value, f"Environment '{env_name}'")
        return cls(**imported_environments)

    def to_dict(self) -> ExecutionEnvironmentDict:
        """Convert the ExecutionEnvironment to a dictionary.

        :return ExecutionEnvironmentDict: A dictionary representation of the ExecutionEnvironment.
        """
        return cast(ExecutionEnvironmentDict, self._environments)

    @property
    def hash_id(self) -> str:
        """Get the hash_id property.

        :return: A 64-character hexadecimal hash_id string.
        """
        return self._hash_id

    @property
    def python(self) -> PythonInfo | None:
        """Get the Python property.

        Returns the :class:`PythonInfo` instance if the 'python'
        execution environment is present, otherwise returns ``None``.

        :return PythonInfo | None: The Python info.
        :raises SimpleBenchTypeError: If the 'python' environment is not of type PythonInfo.
        """
        if 'python' in self._environments:
            python_env = self._environments['python']
            if isinstance(python_env, PythonInfo):
                return python_env
            raise SimpleBenchTypeError(
                "The 'python' environment is not of type PythonInfo",
                tag=_ExecutionEnvironmentErrorTag.INVALID_ENVIRONMENT_TYPE,
            )
        return None

    def __getitem__(self, key: str) -> Environment:
        return self._environments[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._environments)

    def __len__(self) -> int:
        return len(self._environments)

    def __contains__(self, key: object) -> bool:
        return key in self._environments

    def __repr__(self) -> str:
        return f'{self.__class__.__name__}({dict(self._environments)!r})'

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, ExecutionEnvironment):
            return NotImplemented
        return self.hash_id == other.hash_id

    def __hash__(self) -> int:
        return hash(self.hash_id)
