"""Error tags for JSONCPUInfo reporter base class."""
from simplebench.enums import enum_docstrings
from simplebench.exceptions import ErrorTag


@enum_docstrings
class _CPUInfoErrorTag(ErrorTag):
    """Error tags for JSONCPUInfo reporter base class."""
    JSON_SCHEMA_VALIDATION_ERROR = "JSON_SCHEMA_VALIDATION_ERROR"
    """The JSON data does not conform to the expected schema."""
    INVALID_VERSION_TYPE = "INVALID_VERSION_TYPE"
    """The 'version' property is not of type 'int'."""
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
    """The 'version' property is an unsupported version number."""
    INVALID_BRAND_RAW_TYPE = "INVALID_BRAND_RAW_TYPE"
    """The 'brand_raw' property is not of type 'str'."""
    INVALID_BRAND_RAW_VALUE_BLANK_STRING = "INVALID_BRAND_RAW_VALUE_BLANK_STRING"
    """The 'brand_raw' property is a blank string."""
    INVALID_ARCH_STRING_RAW_TYPE = "INVALID_ARCH_STRING_RAW_TYPE"
    """The 'arch_string_raw' property is not of type 'str'."""
    INVALID_ARCH_STRING_RAW_VALUE_BLANK_STRING = "INVALID_ARCH_STRING_RAW_VALUE_BLANK_STRING"
    """The 'arch_string_raw' property is a blank string."""
    INVALID_COUNT_TYPE = "INVALID_COUNT_TYPE"
    """The 'count' property is not of type 'int'."""
    INVALID_COUNT_VALUE = "INVALID_COUNT_VALUE"
    """The 'count' property is less than one."""
    INVALID_ARCH_TYPE = "INVALID_ARCH_TYPE"
    """The 'arch' property is not of type 'str'."""
    INVALID_ARCH_VALUE_EMPTY_OR_BLANK_STRING = "INVALID_ARCH_VALUE_EMPTY_OR_BLANK_STRING"
    """The 'arch' property is an empty or blank string."""
    INVALID_BITS_TYPE = "INVALID_BITS_TYPE"
    """The 'bits' property is not of type 'int'."""
    INVALID_BITS_VALUE = "INVALID_BITS_VALUE"
    """The 'bits' property is less than 16."""
    INVALID_HASH_ID_PROPERTY_TYPE = "INVALID_HASH_ID_PROPERTY_TYPE"
    """The 'hash_id' property is not of type 'str'."""
    INVALID_HASH_ID_PROPERTY_VALUE = "INVALID_HASH_ID_PROPERTY_VALUE"
    """The 'hash_id' property is not a valid SHA-256 hexadecimal string or empty"""
    INVALID_DATA_ARG_TYPE = "INVALID_DATA_ARG_TYPE"
    """The 'data' argument is not of type 'dict'."""
    INVALID_DATA_ARG_EXTRA_KEYS = "INVALID_DATA_ARG_EXTRA_KEYS"
    """The 'data' argument contains unexpected extra keys."""
    INVALID_DATA_ARG_MISSING_KEYS = "INVALID_DATA_ARG_MISSING_KEYS"
    """The 'data' argument is missing required keys."""
