"""Builder exception ErrorTags for JSON report objects."""
from simplebench.enums import enum_docstrings
from simplebench.exceptions import ErrorTag


@enum_docstrings
class _HydratorErrorTag(ErrorTag):
    """Builder exception ErrorTags for JSON report objects."""
    INVALID_DATA_KEY = "INVALID_DATA_KEY"
    "Invalid `data` key. Not listed in `allowed` keys."
    INVALID_MATCH_ON_VALUE = "INVALID_MATCH_ON_VALUE"
    "Invalid `match_on` value. Not listed in `allowed` keys."
    INVALID_ALLOWED_EMPTY = "INVALID_ALLOWED_EMPTY"
    "Invalid `allowed` value. The dictionary cannot be empty."
    INVALID_SKIP_VALUE = "INVALID_SKIP_VALUE"
    "Invalid `skip` value. Not listed in `allowed` keys."
    INVALID_ALLOWED_VALUE_TYPE = "INVALID_ALLOWED_VALUE_TYPE"
    "Invalid `allowed` value. Expected a `type`."
    INVALID_SKIP_TYPE = "INVALID_SKIP_TYPE"
    "Invalid `skip` type: Must be an Iterable of str."
    INVALID_SKIP_ITEM_TYPE = "INVALID_SKIP_ITEM_TYPE"
    "Invalid type for an item in the `skip` parameter. Expected `str`."
    INVALID_ALLOWED_TYPE = "INVALID_ALLOWED_TYPES_TYPE"
    "Invalid `allowed` type: Must be a dict."
    INVALID_OPTIONAL_TYPE = "INVALID_OPTIONAL_TYPE_TYPE"
    "Invalid `optional` type: Must be an Iterable of str."
    INVALID_OPTIONAL_ITEM_TYPE = "INVALID_OPTIONAL_ITEM_TYPE"
    "Invalid type for an item in the `optional` parameter. Expected `str`."
    INVALID_OPTIONAL_ITEM_VALUE = "INVALID_OPTIONAL_ITEM_VALUE"
    "Invalid value for an item in the `optional` parameter. Not listed in `allowed` keys."
    INVALID_ERROR_TAG_TYPE = "INVALID_ERROR_TAG_TYPE"
    "Invalid type for the `error_tag` parameter. Expected type `ErrorTag`."
    INVALID_DATA_TYPE = "INVALID_DATA_TYPE"
    "Invalid type for the `data` parameter. Expected type `dict`."
    INVALID_DATA_KEY_TYPE = "INVALID_DATA_KEY_TYPE"
    "Invalid key type in the `data` parameter. Expected type `str`."
    INVALID_OPTIONAL_FIELDS_TYPE = "INVALID_OPTIONAL_FIELDS_TYPE"
    "Invalid type for the `optional_fields` parameter. Expected Iterable of `str`."
    INVALID_OPTIONAL_FIELDS_ITEM_TYPE = "INVALID_OPTIONAL_FIELDS_ITEM_TYPE"
    "Invalid type for an item in the `optional_fields` parameter. Expected `str`."
