"""Exceptions for JSON stats summary report."""
from simplebench.enums import enum_docstrings
from simplebench.exceptions import ErrorTag


@enum_docstrings
class _JSONStatsErrorTag(ErrorTag):
    """Error tags for JSON stats summary exceptions."""
    INVALID_TYPE_TYPE = "INVALID_TYPE_TYPE"
    """The type is not of type string."""
    INVALID_TYPE_VALUE = "INVALID_TYPE_VALUE"
    """The type has an invalid value."""
    INVALID_UNIT_TYPE = "INVALID_UNIT_TYPE"
    """The unit is not of type string."""
    INVALID_UNIT_VALUE = "INVALID_UNIT_VALUE"
    """The unit has an invalid value. Cannot be an empty string."""
    INVALID_SCALE_TYPE = "INVALID_SCALE_TYPE"
    """The scale is not of type float."""
    INVALID_SCALE_VALUE = "INVALID_SCALE_VALUE"
    """The scale has an invalid value. Must be > 0.0"""
    INVALID_N_TYPE = "INVALID_N_TYPE"
    """The n is not of type integer."""
    INVALID_N_VALUE = "INVALID_N_VALUE"
    """The n has an invalid value. Must be >= 0."""
    INVALID_ROUNDS_TYPE = "INVALID_ROUNDS_TYPE"
    """The rounds is not of type integer."""
    INVALID_ROUNDS_VALUE = "INVALID_ROUNDS_VALUE"
    """The rounds has an invalid value. Must be >= 1."""
    INVALID_MEAN_TYPE = "INVALID_MEAN_TYPE"
    """The mean is not of type float."""
    INVALID_MEDIAN_TYPE = "INVALID_MEDIAN_TYPE"
    """The median is not of type float."""
    INVALID_MINIMUM_TYPE = "INVALID_MINIMUM_TYPE"
    """The minimum is not of type float."""
    INVALID_MAXIMUM_TYPE = "INVALID_MAXIMUM_TYPE"
    """The maximum is not of type float."""
    INVALID_STANDARD_DEVIATION_TYPE = "INVALID_STANDARD_DEVIATION_TYPE"
    """The standard_deviation is not of type float."""
    INVALID_RELATIVE_STANDARD_DEVIATION_TYPE = "INVALID_RELATIVE_STANDARD_DEVIATION_TYPE"
    """The relative_standard_deviation is not of type float."""
    INVALID_PERCENTILES_TYPE = "INVALID_PERCENTILES_TYPE"
    """The percentiles is not of type list."""
    INVALID_PERCENTILES_CONTENT_TYPE = "INVALID_PERCENTILES_CONTENT_TYPE"
    """One or more items in percentiles are not of type float."""
    INVALID_VERSION_TYPE = "INVALID_VERSION_TYPE"
    """The version is not of type integer."""
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
    """The version is not supported."""
