"""ErrorTags for PythonInfo classes"""
from simplebench.enums import enum_docstrings
from simplebench.exceptions import ErrorTag


@enum_docstrings
class _PythonInfoErrorTag(ErrorTag):
    """ErrorTags for PythonInfo classes"""
    INVALID_COMPILER_PROPERTY_TYPE = "INVALID_COMPILER_PROPERTY_TYPE"
    """Invalid compiler property type"""
    INVALID_COMPILER_PROPERTY_VALUE = "INVALID_COMPILER_PROPERTY_VALUE"
    """Invalid compiler property value"""
    INVALID_IMPLEMENTATION_PROPERTY_TYPE = "INVALID_IMPLEMENTATION_PROPERTY_TYPE"
    """Invalid implementation property type"""
    INVALID_IMPLEMENTATION_PROPERTY_VALUE = "INVALID_IMPLEMENTATION_PROPERTY_VALUE"
    """Invalid implementation property value"""
    INVALID_IMPLEMENTATION_VERSION_PROPERTY_TYPE = "INVALID_IMPLEMENTATION_VERSION_PROPERTY_TYPE"
    """Invalid implementation version property type"""
    INVALID_IMPLEMENTATION_VERSION_PROPERTY_VALUE = "INVALID_IMPLEMENTATION_VERSION_PROPERTY_VALUE"
    """Invalid implementation version property value"""
    INVALID_PYTHON_VERSION_PROPERTY_TYPE = "INVALID_PYTHON_VERSION_PROPERTY_TYPE"
    """Invalid Python version property type"""
    INVALID_PYTHON_VERSION_PROPERTY_VALUE = "INVALID_PYTHON_VERSION_PROPERTY_VALUE"
    """Invalid Python version property value"""
    INVALID_BUILD_PROPERTY_TYPE = "INVALID_BUILD_PROPERTY_TYPE"
    """Invalid build property type"""
    INVALID_BUILD_PROPERTY_VALUE = "INVALID_BUILD_PROPERTY_VALUE"
    """Invalid build property value"""
    INVALID_RELEASE_PROPERTY_TYPE = "INVALID_RELEASE_PROPERTY_TYPE"
    """Invalid release property type"""
    INVALID_RELEASE_PROPERTY_VALUE = "INVALID_RELEASE_PROPERTY_VALUE"
    """Invalid release property value"""
    INVALID_SYSTEM_PROPERTY_TYPE = "INVALID_SYSTEM_PROPERTY_TYPE"
    """Invalid system property type"""
    INVALID_SYSTEM_PROPERTY_VALUE = "INVALID_SYSTEM_PROPERTY_VALUE"
    """Invalid system property value"""
    INVALID_HASH_ID_PROPERTY_TYPE = "INVALID_HASH_ID_PROPERTY_TYPE"
    """Invalid hash ID property type"""
    INVALID_HASH_ID_PROPERTY_VALUE = "INVALID_HASH_ID_PROPERTY_VALUE"
    """Invalid hash ID property value"""
    INVALID_DATA_ARG_TYPE = "INVALID_DATA_ARG_TYPE"
    """Invalid data argument type"""
    INVALID_VERSION_TYPE = "INVALID_VERSION_TYPE"
    """Invalid version type"""
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
    """Unsupported version"""
    INVALID_TYPE_TYPE = "INVALID_TYPE_TYPE"
    """Invalid type type"""
    INVALID_TYPE_VALUE = "INVALID_TYPE_VALUE"
    """Invalid type value"""
    INVALID_DATA_ARG_EXTRA_KEYS = "INVALID_DATA_ARG_EXTRA_KEYS"
    """Invalid data argument extra keys"""
    INVALID_DATA_ARG_MISSING_KEYS = "INVALID_DATA_ARG_MISSING_KEYS"
    """Invalid data argument missing keys"""
