"""Test object factories for the simplebench framework.

This package provides a collection of factory functions for creating test instances
of various classes used in the simplebench framework. The factories are split
into domain-specific modules for better organization and maintainability.

The main factory functions are exposed at the package level for easy access,
so you can import them directly from `tests.factories`.

Example:
    from tests.factories import case_factory, reporter_factory

The cache for all factories can be cleared by calling `clear_cache()`.
"""
from ..cache_factory import clear_cache

from ._primitives import (
    n_factory,
    path_factory,
    case_group_factory,
    default_case_group,
    title_factory,
    default_title,
    subdir_factory,
    default_subdir,
    sections_factory,
    default_sections,
    targets_factory,
    default_targets,
    default_targets_factory,
    default_default_targets,
    formats_factory,
    default_formats,
    output_format_factory,
    default_output_format,
    description_factory,
    default_description,
    reporter_name_factory,
    default_reporter_name,
    choice_name_factory,
    flag_name_factory,
    default_choice_name,
    choice_flags_factory,
    default_choice_flags,
    flag_type_factory,
    default_flag_type,
    file_suffix_factory,
    default_file_suffix,
    file_unique_factory,
    default_file_unique,
    file_append_factory,
    default_file_append,
    report_output_factory,
    default_report_output,
    iterations_factory,
    default_iterations,
    warmup_iterations_factory,
    default_warmup_iterations,
    rounds_factory,
    default_rounds,
    min_time_factory,
    default_min_time,
    max_time_factory,
    default_max_time,
    variation_cols_factory,
    kwargs_variations_factory,
    total_elapsed_factory,
    interval_unit_factory,
    interval_scale_factory,
    ops_per_interval_unit_factory,
    ops_per_interval_scale_factory,
    memory_unit_factory,
    memory_scale_factory,
    variation_marks_factory,
)
from ._utils import (
    DefaultExtra,
    extra_factory,
    default_extra,
)
from .argparse import (
    namespace_factory,
    argument_parser_factory,
    boolean_flag_factory,
    list_of_strings_flag_factory,
    reporter_namespace_factory,
)
from .case import (
    case_factory,
    session_factory,
    runner_factory,
    default_runner,
    case_kwargs_factory,
    minimal_case_kwargs_factory,
    default_minimal_case_kwargs,
    default_benchcase,
)
from .reporter import (
    reporter_factory,
    choice_factory,
    choices_factory,
    reporter_kwargs_factory,
    default_reporter_kwargs,
    choice_conf_kwargs_factory,
    default_choice_conf_kwargs,
    choices_conf_kwargs_factory,
    default_choices_conf_kwargs,
    choice_conf_factory,
    default_choice_conf,
    choices_conf_factory,
    default_choices_conf,
    report_parameters_factory,
    FactoryReporter,
    ConfiguredReporterOptions,
    default_options_type,
)
from .results import (
    results_kwargs_factory,
    results_extra_info_factory,
    iterations_sequence_factory,
    peak_memory_factory,
    memory_factory,
    per_round_timings_factory,
    ops_per_interval_factory,
)
from .reporter_callback import default_reporter_callback
from .reporter_options import (
    reporter_options_type_factory,
    default_reporter_options_type,
    reporter_options_factory,
    default_reporter_options,
    reporter_options_tuple_factory,
    default_reporter_options_tuple,
)

__all__ = [
    # Cache control
    'clear_cache',

    # Primitives factories
    'n_factory',
    'path_factory',
    'case_group_factory',
    'default_case_group',
    'title_factory',
    'default_title',
    'subdir_factory',
    'default_subdir',
    'sections_factory',
    'default_sections',
    'targets_factory',
    'default_targets',
    'default_targets_factory',
    'default_default_targets',
    'formats_factory',
    'default_formats',
    'output_format_factory',
    'default_output_format',
    'description_factory',
    'default_description',
    'reporter_name_factory',
    'default_reporter_name',
    'choice_name_factory',
    'flag_name_factory',
    'default_choice_name',
    'choice_flags_factory',
    'default_choice_flags',
    'flag_type_factory',
    'default_flag_type',
    'file_suffix_factory',
    'default_file_suffix',
    'file_unique_factory',
    'default_file_unique',
    'file_append_factory',
    'default_file_append',
    'report_output_factory',
    'default_report_output',
    'iterations_factory',
    'default_iterations',
    'warmup_iterations_factory',
    'default_warmup_iterations',
    'rounds_factory',
    'default_rounds',
    'min_time_factory',
    'default_min_time',
    'max_time_factory',
    'default_max_time',
    'variation_cols_factory',
    'kwargs_variations_factory',
    'total_elapsed_factory',
    'interval_unit_factory',
    'interval_scale_factory',
    'ops_per_interval_unit_factory',
    'ops_per_interval_scale_factory',
    'memory_unit_factory',
    'memory_scale_factory',
    'variation_marks_factory',

    # Utils factories
    'DefaultExtra',
    'extra_factory',
    'default_extra',

    # Argparse factories
    'namespace_factory',
    'argument_parser_factory',
    'boolean_flag_factory',
    'list_of_strings_flag_factory',
    'reporter_namespace_factory',

    # Case factories
    'case_factory',
    'session_factory',
    'runner_factory',
    'default_runner',
    'case_kwargs_factory',
    'minimal_case_kwargs_factory',
    'default_minimal_case_kwargs',
    'default_benchcase',

    # Reporter factories
    'reporter_factory',
    'choice_factory',
    'choices_factory',
    'reporter_kwargs_factory',
    'default_reporter_kwargs',
    'reporter_options_type_factory',
    'default_reporter_options_type',
    'reporter_options_factory',
    'default_reporter_options',
    'reporter_options_tuple_factory',
    'default_reporter_options_tuple',
    'choice_conf_kwargs_factory',
    'default_choice_conf_kwargs',
    'choices_conf_kwargs_factory',
    'default_choices_conf_kwargs',
    'choice_conf_factory',
    'default_choice_conf',
    'choices_conf_factory',
    'default_choices_conf',
    'report_parameters_factory',
    'default_reporter_callback',
    'FactoryReporter',
    'ConfiguredReporterOptions',
    'default_options_type',

    # Results factories
    'results_kwargs_factory',
    'results_extra_info_factory',
    'iterations_sequence_factory',
    'peak_memory_factory',
    'memory_factory',
    'per_round_timings_factory',
    'ops_per_interval_factory',
]
