"""Validator functions for SimpleBench."""
from simplebench.validators._error_tags.validators import _ValidatorsErrorTag

from ._typed_dict import is_typed_dict_mimic, typed_dict_mimic
from .core_data_types import (
    is_core_data,
    is_core_data_mapping,
    is_core_data_primitive,
    is_core_data_primitive_type,
    is_core_data_sequence,
    is_core_data_set,
    is_immutable_core_data,
    validate_core_data,
    validate_core_data_mapping,
    validate_core_data_sequence,
    validate_core_data_set,
    validate_immutable_core_data,
    validate_immutable_core_data_mapping,
    validate_immutable_core_data_sequence,
    validate_immutable_core_data_set,
)
from .dates_and_times import validate_iso8601_datetime
from .identifiers import validate_namespaced_identifier
from .misc import (
    validate_bool,
    validate_dirpath,
    validate_filename,
    validate_float,
    validate_float_range,
    validate_frozenset_of_type,
    validate_int,
    validate_int_range,
    validate_non_negative_float,
    validate_non_negative_int,
    validate_positive_float,
    validate_positive_int,
    validate_sequence_of_numbers,
    validate_sequence_of_str,
)
from .strings import (
    validate_non_blank_string,
    validate_non_blank_string_or_is_none,
    validate_string,
    validate_string_with_regex,
)
from .types import validate_type
from .validate_iterable_of_type import validate_iterable_of_type
from .validate_sequence_of_type import validate_sequence_of_type

__all__ = [
    "typed_dict_mimic",
    "is_typed_dict_mimic",
    "is_core_data",
    "is_core_data_primitive",
    "is_core_data_primitive_type",
    "is_core_data_mapping",
    "is_core_data_sequence",
    "is_core_data_set",
    "is_immutable_core_data",
    "_ValidatorsErrorTag",
    "validate_bool",
    "validate_core_data",
    "validate_core_data_sequence",
    "validate_core_data_set",
    "validate_core_data_mapping",
    "validate_dirpath",
    "validate_filename",
    "validate_float",
    "validate_float_range",
    "validate_frozenset_of_type",
    "validate_immutable_core_data",
    "validate_immutable_core_data_mapping",
    "validate_immutable_core_data_sequence",
    "validate_immutable_core_data_set",
    "validate_int",
    "validate_int_range",
    "validate_iso8601_datetime",
    "validate_iterable_of_type",
    "validate_namespaced_identifier",
    "validate_non_blank_string_or_is_none",
    "validate_non_blank_string",
    "validate_non_negative_float",
    "validate_non_negative_int",
    "validate_positive_float",
    "validate_positive_int",
    "validate_sequence_of_numbers",
    "validate_sequence_of_str",
    "validate_sequence_of_type",
    "validate_string",
    "validate_string_with_regex",
    "validate_type",
    "validate_string",
    "validate_string_with_regex",
    "validate_type",
]
