"""Exceptions for the simplebench.reporters.interfaces module."""
from simplebench.exceptions.base import ErrorTag
from simplebench.enums import enum_docstrings


@enum_docstrings
class ReporterErrorTag(ErrorTag):
    """ErrorTags for exceptions in the reporters.interfaces module."""
    EMPTY_TARGETS_ARG_VALUE = "EMPTY_TARGETS_ARG_VALUE"
    """The targets arg cannot be an empty sequence"""
    INVALID_DEFAULT_TARGETS_ARG_TYPE = "INVALID_DEFAULT_TARGETS_ARG_TYPE"
    """Something other than a set of Target enums or None was passed as the default_targets arg"""
    INVALID_DEFAULT_TARGETS_ENTRY_TYPE = "INVALID_DEFAULT_TARGETS_ENTRY_TYPE"
    """Something other than a Target enum was found in the default_targets arg"""
    INVALID_SUBDIR_ARG_TYPE = "INVALID_SUBDIR_ARG_TYPE"
    """Something other than a string was passed as the default_subdir arg"""
    INVALID_SUBDIR_ARG_VALUE = "INVALID_SUBDIR_ARG_VALUE"
    """The default_subdir arg must be an alphanumeric string (a-z, A-Z, 0-9) or an empty string"""
    SUBDIR_TOO_LONG = "SUBDIR_TOO_LONG"
    """The subdir arg cannot be longer than 64 characters."""
    NAME_INVALID_ARG_TYPE = "NAME_INVALID_ARG_TYPE"
    """Something other than a string was passed as the name arg"""
    NAME_INVALID_ARG_VALUE = "NAME_INVALID_ARG_VALUE"
    """The name arg cannot be an empty string"""
    DESCRIPTION_INVALID_ARG_TYPE = "DESCRIPTION_INVALID_ARG_TYPE"
    """Something other than a string was passed as the description arg"""
    DESCRIPTION_INVALID_ARG_VALUE = "DESCRIPTION_INVALID_ARG_VALUE"
    """The description arg cannot be an empty string"""
    INVALID_SECTIONS_ARG_TYPE = "INVALID_SECTIONS_ARG_TYPE"
    """Something other than a sequence of Section enums was passed as the sections arg"""
    EMPTY_SECTIONS_ARG_VALUE = "EMPTY_SECTIONS_ARG_VALUE"
    """The sections arg cannot be an empty sequence (can be Section.NULL if needed)"""

    REPORTER_OPTIONS_NOT_IMPLEMENTED = "REPORTER_OPTIONS_NOT_IMPLEMENTED"
    """The ReporterOptions could not be found in the Case, Choice, or default options."""
    HARDCODED_DEFAULT_OPTIONS_NOT_IMPLEMENTED = "HARDCODED_DEFAULT_OPTIONS_NOT_IMPLEMENTED"
    """The Reporter.__HARDCODED_DEFAULT_OPTIONS property must be initialized with a
    ReporterOptions subclass instance by subclasses"""
    CHOICES_NOT_IMPLEMENTED = "CHOICES_NOT_IMPLEMENTED"
    """The Reporter.choices property must be implemented in subclasses"""
    NAME_NOT_IMPLEMENTED = "NAME_NOT_IMPLEMENTED"
    """The Reporter.name property must be initialized as a str by subclasses"""
    NAME_INVALID_VALUE = "NAME_INVALID_VALUE"
    """The Reporter.name property must be initialized as a non-empty string by subclasses"""
    OPTIONS_TYPE_INVALID_VALUE = "OPTIONS_TYPE_INVALID_VALUE"
    """The Reporter.options_type property must be a subclass type of ReporterOptions or None"""
    DESCRIPTION_NOT_IMPLEMENTED = "DESCRIPTION_NOT_IMPLEMENTED"
    """The Reporter.description property must be initialized as a str by subclasses"""
    DESCRIPTION_INVALID_VALUE = "DESCRIPTION_INVALID_VALUE"
    """The Reporter.description property must be initialized as a string by subclasses"""
    FILE_SUFFIX_INVALID_ARG_TYPE = "FILE_SUFFIX_INVALID_ARG_TYPE"
    """Something other than a str was passed as the file_suffix argument to the Reporter constructor"""
    FILE_SUFFIX_INVALID_ARG_VALUE = "FILE_SUFFIX_INVALID_ARG_VALUE"
    """The file_suffix argument passed to the Reporter constructor contained non-alphanumeric characters"""
    FILE_SUFFIX_ARG_TOO_LONG = "FILE_SUFFIX_ARG_TOO_LONG"
    """The file_suffix argument passed to the Reporter constructor exceeded the maximum length of 10 characters"""
    FILE_UNIQUE_INVALID_ARG_TYPE = "FILE_UNIQUE_INVALID_ARG_TYPE"
    """Something other than a bool was passed as the file_unique argument to the Reporter constructor"""
    FILE_APPEND_INVALID_ARG_TYPE = "FILE_APPEND_INVALID_ARG_TYPE"
    """Something other than a bool was passed as the file_append argument to the Reporter constructor"""
    FILE_UNIQUE_AND_APPEND_MUTUALLY_EXCLUSIVE = "FILE_UNIQUE_AND_APPEND_MUTUALLY_EXCLUSIVE"
    """file_unique and file_append arguments are mutually exclusive and cannot both be True"""
    RUN_REPORT_NOT_IMPLEMENTED = "RUN_REPORT_NOT_IMPLEMENTED"
    """The Reporter.run_report() method must be implemented by subclasses"""
    ADD_FLAGS_UNSUPPORTED_FLAG_TYPE = "ADD_FLAGS_UNSUPPORTED_FLAG_TYPE"
    """The Reporter.add_flags_to_argparse() method only supports flags of type
    FlagType.BOOLEAN or FlagType.TARGET_LIST"""
    ADD_LIST_OF_TARGETS_FLAGS_INVALID_CHOICE_ARG_TYPE = (
        "ADD_LIST_OF_TARGETS_FLAGS_INVALID_CHOICE_ARG_TYPE")
    """Something other than a Choice instance was passed to the Reporter.add_list_of_targets_flags() method"""
    ADD_BOOLEAN_FLAGS_INVALID_CHOICE_ARG_TYPE = "ADD_BOOLEAN_FLAGS_INVALID_CHOICE_ARG_TYPE"
    """Something other than a Choice instance was passed to the Reporter.add_boolean_flags() method"""
    FORMATS_NOT_IMPLEMENTED = "FORMATS_NOT_IMPLEMENTED"
    """The Reporter.formats property must be implemented in subclasses"""
    INVALID_FORMATS_ENTRY_TYPE = "INVALID_FORMATS_ENTRY_TYPE"
    """Something other than a Format enum was found in the formats argument."""
    SECTIONS_NOT_IMPLEMENTED = "SECTIONS_NOT_IMPLEMENTED"
    """The Reporter.sections property must be implemented in subclasses"""
    INVALID_SECTIONS_ENTRY_TYPE = "INVALID_SECTIONS_ENTRY_TYPE"
    """Something other than a Section enum was found in the sections argument."""
    TARGETS_NOT_IMPLEMENTED = "TARGETS_NOT_IMPLEMENTED"
    """The Reporter.targets property must be implemented in subclasses"""
    INVALID_TARGETS_ENTRY_TYPE = "INVALID_TARGETS_ENTRY_TYPE"
    """Something other than a Target enum was found in the targets argument."""
    REPORT_INVALID_ARGS_ARG_TYPE = "REPORT_INVALID_ARGS_ARG_TYPE"
    """Something other than a Namespace instance was passed to the Reporter.report() method as the args argument"""
    REPORT_INVALID_CASE_ARG = "REPORT_INVALID_CASE_ARG"
    """Something other than a Case instance was passed to the Reporter.report() method"""
    REPORT_INVALID_CHOICE_ARG = "REPORT_INVALID_CHOICE_ARG"
    """Something other than a Choice instance was passed to the Reporter.report() method"""
    REPORT_INVALID_SESSION_ARG = "REPORT_INVALID_SESSION_ARG"
    """Something other than a Session instance was passed to the Reporter.report() method"""
    REPORT_INVALID_PATH_ARG = "REPORT_INVALID_PATH_ARG"
    """Something other than a Path instance was passed to the Reporter.report() method"""
    REPORT_INVALID_CALLBACK_ARG = "REPORT_INVALID_CALLBACK_ARG"
    """Something other than a callable was passed to the Reporter.report() method as the callback argument"""
    REPORT_UNSUPPORTED_SECTION = "REPORT_UNSUPPORTED_SECTION"
    """An unsupported Section was passed to the Reporter.report() method in the Choice.sections"""
    REPORT_UNSUPPORTED_TARGET = "REPORT_UNSUPPORTED_TARGET"
    """An unsupported Target was passed to the Reporter.report() method in the Choice.targets"""
    REPORT_UNSUPPORTED_FORMAT = "REPORT_UNSUPPORTED_FORMAT"
    """An unsupported Format was passed to the Reporter.report() method in the Choice.formats"""
    INVALID_CHOICES_ARG_TYPE = "INVALID_CHOICES_ARG_TYPE"
    """Something other than a Choices instance was passed as the choices argument to the Reporter constructor"""
    INVALID_CHOICES_ARG_VALUE = "INVALID_CHOICES_ARG_VALUE"
    """The choices argument passed to the Reporter constructor must contain at least one Choice"""
    ADD_CHOICE_UNSUPPORTED_SECTION = "ADD_CHOICE_UNSUPPORTED_SECTION"
    """A Section in the Choice instance passed to the Reporter.add_choice() method is not supported by the Reporter"""
    ADD_CHOICE_INVALID_ARG_TYPE = "ADD_CHOICE_INVALID_ARG_TYPE"
    """Something other than a Choice instance was passed to the Reporter.add_choice() method"""
    ADD_CHOICE_UNSUPPORTED_TARGET = "ADD_CHOICE_UNSUPPORTED_TARGET"
    """A Target in the Choice instance passed to the Reporter.add_choice() method is not supported by the Reporter"""
    ADD_CHOICE_UNSUPPORTED_FORMAT = "ADD_CHOICE_UNSUPPORTED_FORMAT"
    """A Format in the Choice instance passed to the Reporter.add_choice() method is not supported by the Reporter"""
    ADD_FLAGS_INVALID_PARSER_ARG_TYPE = "ADD_FLAGS_INVALID_PARSER_ARG_TYPE"
    """Something other than an ArgumentParser instance was passed to the Reporter.add_flags_to_argparse() method"""
    TARGET_FILESYSTEM_INVALID_PATH_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_PATH_ARG_TYPE"
    """Something other than a Path instance was passed to the Reporter.target_filesystem() method"""
    TARGET_FILESYSTEM_INVALID_SUBDIR_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_SUBDIR_ARG_TYPE"
    """Something other than a string was passed to the Reporter.target_filesystem() method as the subdir argument"""
    TARGET_FILESYSTEM_INVALID_SUBDIR_ARG_VALUE = "TARGET_FILESYSTEM_INVALID_SUBDIR_ARG_VALUE"
    """The subdir argument passed to the Reporter.target_filesystem() method
    contains non-alphanumeric characters"""
    TARGET_FILESYSTEM_INVALID_APPEND_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_APPEND_ARG_TYPE"
    """Something other than a bool was passed to the Reporter.target_filesystem() method as the append argument"""
    TARGET_FILESYSTEM_INVALID_UNIQUE_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_UNIQUE_ARG_TYPE"
    """Something other than a bool was passed to the Reporter.target_filesystem() method as the unique argument"""
    TARGET_FILESYSTEM_INVALID_OUTPUT_ARG_TYPE = "TARGET_FILESYSTEM_INVALID_OUTPUT_ARG_TYPE"
    """Something other than a str, bytes, rich.Text, or rich.Table was passed to the Reporter.target_filesystem()
    method as the output argument"""
    TARGET_FILESYSTEM_APPEND_UNIQUE_INCOMPATIBLE_ARGS = (
        "TARGET_FILESYSTEM_APPEND_UNIQUE_INCOMPATIBLE_ARGS")
    """The append and unique options are not compatible when writing to the filesystem"""
    TARGET_FILESYSTEM_OUTPUT_FILE_EXISTS = "TARGET_FILESYSTEM_OUTPUT_FILE_EXISTS"
    """The output file already exists and the append or unique options were not specified"""
    RUN_REPORT_UNSUPPORTED_SECTION = "RUN_REPORT_UNSUPPORTED_SECTION"
    """An unsupported Section was passed to the reporter's run_report() method"""
    RUN_REPORT_INVALID_CHOICE_OPTIONS_TYPE = "RUN_REPORT_INVALID_CHOICE_OPTIONS_TYPE"
    """Something other than a RichTableChoiceOptions instance was set for a choice option"""
    UNKNOWN_TARGET_IN_ARGS = "UNKNOWN_TARGET_IN_ARGS"
    """An unknown target string was specified in the command-line arguments"""
    UNSUPPORTED_TARGET_IN_ARGS = "UNSUPPORTED_TARGET_IN_ARGS"
    """An unsupported target string was specified in the command-line arguments"""
    SET_DEFAULT_TARGETS_INVALID_TARGETS_ARG_TYPE = "SET_DEFAULT_TARGETS_INVALID_TARGETS_ARG_TYPE"
    """Invalid targets argument type:
    - must be of type `frozenset[Target]` or `None.`"""
    SET_DEFAULT_TARGETS_INVALID_TARGETS_ARG_VALUE = "SET_DEFAULT_TARGETS_INVALID_TARGETS_ARG_VALUE"
    """Invalid targets argument value:
    - must be a `frozenset` of `Target` enum members."""
    SET_DEFAULT_SUBDIR_INVALID_SUBDIR_ARG_TYPE = "SET_DEFAULT_SUBDIR_INVALID_SUBDIR_ARG_TYPE"
    """Invalid subdir argument type:
    - must be of type `str` or `None.`"""
    SET_DEFAULT_SUBDIR_INVALID_SUBDIR_ARG_VALUE = "SET_DEFAULT_SUBDIR_INVALID_SUBDIR_ARG_VALUE"
    """Invalid subdir argument value:
    - must be a `str` of only alphanumeric characters (A-Z, a-z, 0-9) or `None`."""
    GET_OPTIONS_INVALID_OPTIONS_ARG_TYPE = "GET_OPTIONS_INVALID_OPTIONS_ARG_TYPE"
    """Invalid options argument type:
    - must be of type `Iterable[ReporterOptions]` or `None`."""
    GET_OPTIONS_INVALID_OPTIONS_ARG_VALUE = "GET_OPTIONS_INVALID_OPTIONS_ARG_VALUE"
    """Invalid options argument value:
    - options argument iterable contains something other than `ReporterOptions` instances."""
    RENDER_BY_SECTION_UNSUPPORTED_TARGET = "RENDER_BY_SECTION_UNSUPPORTED_TARGET"
    """An unsupported Target was passed to the reporter's render_by_section() method"""
    RENDER_BY_CASE_UNSUPPORTED_TARGET = "RENDER_BY_CASE_UNSUPPORTED_TARGET"
    """An unsupported Target was passed to the reporter's render_by_case() method"""
    RENDER_NOT_IMPLEMENTED = "RENDER_NOT_IMPLEMENTED"
    """The Reporter.render() method must be implemented by subclasses"""
    RICH_TEXT_TO_PLAIN_TEXT_INVALID_WIDTH_ARG_TYPE = "RICH_TEXT_TO_PLAIN_TEXT_INVALID_WIDTH_ARG_TYPE"
    """Something other than an int was passed to the Reporter.rich_text_to_plain_text() method
    as the virtual_console_width argument"""
    RICH_TEXT_TO_PLAIN_TEXT_INVALID_WIDTH_ARG_VALUE = "RICH_TEXT_TO_PLAIN_TEXT_INVALID_WIDTH_ARG_VALUE"
    """The virtual_console_width argument passed to the Reporter.rich_text_to_plain_text() method
    is outside the valid range"""
    RICH_TEXT_TO_PLAIN_TEXT_INVALID_RICH_TEXT_ARG_TYPE = "RICH_TEXT_TO_PLAIN_TEXT_INVALID_RICH_TEXT_ARG_TYPE"
    """Something other than a rich.Text or rich.Table instance was passed to the
    Reporter.rich_text_to_plain_text() method as the rich_text argument"""
