"""JSON CPUInfo version 1 class.

The CPUInfo class represents a version 1 JSON CPUInfo.

It provides methods to convert to and from dictionary representations
and includes schema validation specific to version 1 reports.

The version 1 CPUInfo is the first stable version of the JSON CPUInfo format
and serves as a foundation for future versions.

As the foundational version, this class is considered immutable. Future versions
will inherit from this class to extend its functionality, but this implementation
will not be changed.
"""
import copy
import hashlib
import json

from simplebench import environment
from simplebench.environment import CPUInfoDictType
from simplebench.report.base import BaseCPUInfo, JSONSchema

from . import validate
from .cpu_info_schema import CPUInfoSchema


class CPUInfo(BaseCPUInfo):
    """Class representing a JSON CPUInfo version 1."""

    TYPE: str = CPUInfoSchema.TYPE
    """The JSON CPUInfo type property value for version 1 reports."""

    VERSION: int = CPUInfoSchema.VERSION
    """The JSON CPUInfo version number."""

    SCHEMA: type[JSONSchema] = CPUInfoSchema
    """The JSON schema class for version 1 reports."""


    def __init__(self,
                 *,
                 hash_id: str | None = None,
                 data: CPUInfoDictType | environment.CPUInfo) -> None:
        """Initialize CPUInfo.

        :param str | None hash_id: The unique hash identifier for the CPU information.
            If not provided it will be computed automatically.

            The hash_id must be a 64 character hexadecimal string, an
            empty string, or None.

            The semantics of hash_id are NOT to provide integrity verification of the data,
            but rather to provide a globally unique identifier for the specific CPU information
            for this instance. It can be used to compare CPU information across different systems
            or runs to determine if they represent the same CPU configuration as long
            as the data was generated by the same version of the CPUInfo reporter.

            In other words, two CPUInfo instances with the same hash_id can be assumed to represent
            the same CPU information if they were generated by the same version of the reporter.

            Because the hash_id is derived from the data content, any change to the data
            will result in a different hash_id. This means that the hash_id can be used
            to quickly check if two CPUInfo instances are identical in terms of their
            CPU information and originating source.

            It is recommended to let the hash_id be computed automatically to ensure
            consistency and correctness unless importing data from an external source.
            
            hash_id values are NOT validated against the data content on initialization
            because it is only an opaque identifier, not a data validation mechanism.

        :param CPUInfoDictType | environment.CPUInfo data: The raw CPU information data collected from the system
            using the :package:`cpuinfo` library. It must either be a dictionary or
            an instance of `simplebench.environment.CPUInfo`.

            The dictionary must conform to the following rules:
            - It can have arbitrary keys and values but must be a tree composed of
              dictionaries, lists, strings, numbers, booleans, and nulls.
            - All keys in dictionaries must be non-blank, non-empty strings.
        """
        if isinstance(data, environment.CPUInfo):
            data = data.info
        self._data = validate.data(data)
        self._hash_id = validate.hash_id(hash_id, allow_none=True)

    @property
    def hash_id(self) -> str:
        """Get the hash_id property.

        :return str: The hash_id string.
        """
        if self._hash_id is None:
            serialized = json.dumps(self.data, sort_keys=True, separators=(',', ':'))
            self._hash_id = hashlib.sha256(serialized.encode('utf-8')).hexdigest()
        return self._hash_id

    @property
    def data(self) -> CPUInfoDictType:
        """Get the data property.

        :return CPUInfoDictType: A deep copy of the data dictionary to ensure immutability.
        """
        return copy.deepcopy(self._data)

    @classmethod
    def from_system(cls) -> 'CPUInfo':
        """Create a CPUInfo instance from the current system's CPU information.

        This method collects CPU information using the
        :package:`~simplebench.environment.CPUInfo` library class
        and constructs a CPUInfo instance with the collected data.

        :return CPUInfo: A CPUInfo instance containing the current system's CPU information.
        """

        cpu_data = environment.CPUInfo().info
        return cls(data=cpu_data)

    @classmethod
    def from_dict(cls, data: CPUInfoDictType) -> 'CPUInfo':
        """Create a CPUInfo instance from a dictionary.

        .. code-block:: python
           :caption: Example

           cpu_info = CPUInfo.from_dict(data)


        The dictionary must conform to the expected structure for the CPUInfo
        representation. The 'version' and 'type' properties are validated
        against the class's VERSION and TYPE attributes if they are present.

        :param CPUInfoDictType data: The dictionary containing CPU information.
        :return CPUInfo: A CPUInfo instance.
        """
        allowed_keys = cls.init_params()
        allowed_keys['version'] = int
        allowed_keys['type'] = str

        kwargs = cls.import_data(
            data=data,
            allowed=allowed_keys,
            skip={'version', 'type'},
            optional={'hash_id', 'version', 'type'},
            default={'hash_id': None, 'version': cls.VERSION, 'type': cls.TYPE},
            match_on={'version': cls.VERSION, 'type': cls.TYPE})
        return cls(**kwargs)

    def to_dict(self) -> CPUInfoDictType:
        """Convert the CPUInfo to a dictionary suitable for JSON serialization.

        This includes all properties defined in the :class:`CPUInfoSchema`
        for the version.

        :return dict[str, DataTypes]: A dictionary representation of the CPUInfo.
        """
        property_keys = self.init_params().keys()
        data = {key: getattr(self, key) for key in property_keys}
        data['type'] = self.TYPE
        data['version'] = self.VERSION

        return data
