"""CPUInfo version 1 class.

The CPUInfo class represents a version 1 JSON CPUInfo.

It provides methods to convert to and from dictionary representations
and includes schema validation specific to version 1 reports.

The version 1 CPUInfo is the first stable version of the JSON CPUInfo format
and serves as a foundation for future versions.

As the foundational version, this class is considered immutable. Future versions
will inherit from this class to extend its functionality, but this implementation
will not be changed.
"""
import hashlib
import json
from copy import copy
from types import MappingProxyType
from typing import TYPE_CHECKING, Any, cast

from typeguard import check_type

from simplebench._log import _log
from simplebench.report.base import BaseCPUInfo, JSONSchema
from simplebench.simplebench_types import CoreDataMappingType

from . import _validate
from .cpu_info_schema import CPUInfoSchema
from .typeddict_types import CPUInfoData, ImmutableCPUInfoData, ImmutableCPUInfoDict

if TYPE_CHECKING:
    from simplebench import environment

class CPUInfo(BaseCPUInfo):
    """Class representing a JSON CPUInfo version 1."""

    TYPE: str = CPUInfoSchema.TYPE
    """The JSON CPUInfo type property value for version 1 reports."""

    VERSION: int = CPUInfoSchema.VERSION
    """The JSON CPUInfo version number."""

    SCHEMA: type[JSONSchema] = CPUInfoSchema
    """The JSON schema class for version 1 reports."""

    _init_params_cache: MappingProxyType[str, Any] = MappingProxyType({})
    """Cache for the constructor parameters of the CPUInfo class."""

    @classmethod
    def _data_params(cls) -> MappingProxyType[str, Any]:
        """Get the constructor parameters for the schema data class.

        The parameters are cached after the first call for performance.

        It is returned as a read-only mapping and includes 'type' and 'version'.

        :return MappingProxyType[str, Any]: A read-only mapping of constructor parameter names and types.
        """
        if not cls._init_params_cache:
            params = cls.init_params(CPUInfoData)
            _log.debug("Cached CPUInfo init parameters: %s", params)
            cls._init_params_cache = MappingProxyType(params)
        return cls._init_params_cache

    __slots__ = ('_data', '_hash_id', '_to_dict_cache')

    def __init__(self, *,
                 hash_id: str = '',
                 data: CPUInfoData | None = None,
                 cpu_info: 'environment.CPUInfo | None' = None) -> None:
        """Initialize CPUInfo.

        Only one of `data` or `cpu_info` may be provided.

        :param hash_id: The unique hash identifier for the CPU information.
            If not provided it will be computed automatically.

            The hash_id must be a 64 character hexadecimal string or an empty string.

            The semantics of hash_id are NOT to provide integrity verification of the data,
            but rather to provide a globally unique identifier for the specific CPU information
            for this instance. It can be used to compare CPU information across different systems
            or runs to determine if they represent the same CPU configuration as long
            as the data was generated by the same version of the CPUInfo reporter.

            In other words, two CPUInfo instances with the same hash_id can be assumed to represent
            the same CPU information if they were generated by the same version of the reporter.

            Because the hash_id is derived from the data content, any change to the data
            will result in a different hash_id. This means that the hash_id can be used
            to quickly check if two CPUInfo instances are identical in terms of their
            CPU information and originating source.

            It is recommended to let the hash_id be computed automatically to ensure
            consistency and correctness unless importing data from an external source.

            hash_id values are NOT validated against the data content on initialization
            because it is only an opaque identifier, not a data validation mechanism.
        :type hash_id: str
        :param cpu_info: The CPU information data collected from the system
            It must be an instance of `simplebench.environment.CPUInfo`.
            If provided, the `data` parameter must be None.
        :type cpu_info: environment.CPUInfo | None
        :param CPUInfoData data: The raw CPU information data as a dictionary.
            If provided, the `cpu_info` parameter must be None.
        :type data: CPUInfoData | None
        :raises SimpleBenchTypeError: If any of the parameters are of incorrect type.
        :raises SimpleBenchValueError: If any of the parameters have invalid values.
        """
        if cpu_info is not None:
            if data is not None:
                raise ValueError("Cannot provide both 'data' and 'cpu_info' parameters.")
            data = cpu_info.to_dict()
        self._data: ImmutableCPUInfoData = _validate.data(data)
        # prioritize the passed hash_id, else fetch from data if present, else compute later
        self._hash_id: str = _validate.hash_id(hash_id) or self.data.get('hash_id', '')
        self._to_dict_cache: ImmutableCPUInfoDict | None = None

    @property
    def hash_id(self) -> str:
        """Get the hash_id property.

        We can't use the helper from the base class because we need to
        compute the hash_id based on the data property which is a complex structure
        of dictionaries and lists. So we serialize the data to a sorted JSON string
        and compute the SHA256 hash of that string.

        :return str: The hash_id string.
        """
        if self._hash_id is None:
            serialized = json.dumps(self.data, sort_keys=True, separators=(',', ':'))
            self._hash_id = hashlib.sha256(serialized.encode('utf-8')).hexdigest()
        return self._hash_id

    @property
    def data(self) -> ImmutableCPUInfoData:
        """Get the data property.

        :return ImmutableCoreDataMappingType: An immutable mapping of the CPU information data.
        """
        return self._data

    @classmethod
    def from_dict(cls, data: CPUInfoData) -> 'CPUInfo':
        """Create a CPUInfo instance from a dictionary.

        .. code-block:: python
           :caption: Example

           cpu_info = CPUInfo.from_dict(data)

        The dictionary must conform to the expected structure for the CPUInfo
        representation. The 'version' and 'type' properties are validated
        against the class's VERSION and TYPE attributes if they are present.

        :param CPUInfoDict data: The dictionary containing CPU information.
        :return CPUInfo: A CPUInfo instance.
        """
        allowed_keys = cls._data_params()
        _log.debug("CPUInfo.from_dict allowed keys: %s", allowed_keys)
        _log.debug("CPUInfo.from_dict input data: %s", data)
        kwargs = cls.import_data(
            data=data,
            allowed_fields=allowed_keys,
            skip_fields={'version', 'type'},
            optional_fields={'hash_id', 'version', 'type'},
            defaults={'version': cls.VERSION, 'type': cls.TYPE},
            match_on={'version': cls.VERSION, 'type': cls.TYPE},
        )
        _log.info("CPUInfo.from_dict initialized with kwargs: %s", kwargs)
        validated_data = check_type(kwargs, CPUInfoData)
        hash_id_value = validated_data.get('hash_id', '')
        if 'hash_id' in validated_data:
            del validated_data['hash_id']
        return cls(data=validated_data, hash_id=hash_id_value)

    def to_dict(self) -> ImmutableCPUInfoDict:
        """Returns the CPUInfo as an immutable dictionary suitable for JSON serialization.

        This includes all properties defined in the :class:`CPUInfoSchema`
        for the version 1 CPUInfo.

        :return ImmutableCPUInfoDict: An immutable mapping representation of the CPUInfo.
        """
        if self._to_dict_cache is None:
            cls = self.__class__
            self._to_dict_cache = cast(
                ImmutableCPUInfoDict,
                MappingProxyType(
                    {
                        'type': cls.TYPE,
                        'version': cls.VERSION,
                        'hash_id': self.hash_id,
                        'data': cast(CoreDataMappingType, self.data),
                    }
                ),
            )
        return self._to_dict_cache

    def __eq__(self, other: object) -> bool:
        """Check equality between two CPUInfo instances.

        .. note::
            Triggers the lazy eval properties to be evaluated if they have not been already.
            This ensures that comparisons are made based on the actual values of the properties.

            This can be expensive the first time it is called if many properties
            need to be calculated from many measurements.

            This is unavoidable since equality must reflect the actual state of the object.

        :param other: The other CPUInfo instance to compare with.
        :return bool: True if the two CPUInfo instances are equal, False otherwise.
        """
        if not isinstance(other, CPUInfo):
            return NotImplemented

        return hash(self) == hash(other)

    def __hash__(self) -> int:
        """Compute the hash of the CPUInfo instance.

        The hash is computed from the hash_id.

        .. note::
            Triggers the lazy eval properties to be evaluated if they have not been already.
            This ensures that the hash is based on the actual values of the properties.

            This can be expensive the first time it is called if many properties
            need to be calculated from many measurements. This is unavoidable
            since the hash must reflect the actual state of the object.

        :return int: The hash value of the CPUInfo instance.
        """
        return hash(self.hash_id)

    def __repr__(self) -> str:
        """Get the string representation of the CPUInfo instance.

        :return: The string representation of the CPUInfo.
        """
        # Get the init parameters excluding 'type' and 'version'
        init_params = dict(self._data_params())
        init_params.pop('type', None)
        init_params.pop('version', None)

        calling_args = ', '.join(f'{key}={getattr(self, key)!r}' for key in init_params)
        return f'{self.__class__.__name__}({calling_args})'

    def __getstate__(self) -> tuple[dict[str, Any] | None, tuple[Any, ...]]:
        """Prepare the object's state for pickling, prioritizing size.

        This method ensures that the pickled representation of the RawDataBlock
        is compact. It achieves this by forcing the calculation of any lazy-evaluated
        statistical properties and then excluding any attributes that are not part of the
        public interface of the RawDataBlock from the pickled state. Those excluded attributes
        can be recalculated upon unpickling on demand and do not need to be stored.

        This prioritizes a smaller pickled size and fast subsequent unpickling over
        preserving the lazy-evaluation state across serialization.

        :return: A state tuple for pickling.
        :rtype: tuple[dict[str, Any] | None, tuple[Any, ...]]
        """
        # Sweep all slot attributes to force calculation of any lazy properties.
        # and collect any public attribute values for pickling. The non-public
        # attributes will be excluded from the pickled state and can be
        # recalculated on demand after unpickling. This keeps the pickled
        # representation minimal and about 50% smaller. Which is significant
        # for large datasets.
        # 'version' and 'type' are excluded as they are class constants not
        # instance attributes and can be inferred.
        public_attrs = dict(self._data_params())
        public_attrs.pop('type', None)
        public_attrs.pop('version', None)
        slot_values: list[Any] = []
        for slot in self.__slots__:
            attr_name = slot.lstrip('_')
            if attr_name in public_attrs:
                slot_values.append(getattr(self, attr_name))
            else:
                slot_values.append(None)

        # Build the state tuple for a __slots__ class. The first element is for
        # __dict__ (None in our case) and the second is a tuple of the slotted values.
        state = tuple(slot_values)
        return (None, state)

    def __setstate__(self, state: tuple[dict[str, Any] | None, tuple[Any, ...]]) -> None:
        """Restore the object's state from a pickled representation.

        This method is the counterpart to `__getstate__`. It takes the state
        tuple and repopulates the instance's `__slots__`.

        .. note::
            This method bypasses `__init__`, which is standard for unpickling.

        :param state: The state tuple from unpickling.
        :type state: tuple[dict[str, Any] | None, tuple[Any, ...]]
        """
        # The first element of the state tuple is for __dict__, which is None for this class.
        # The second element is a tuple of values for the __slots__.
        slot_values = state[1]
        for slot, value in zip(self.__slots__, slot_values, strict=True):
            # Use object.__setattr__ to bypass our immutable setters.
            object.__setattr__(self, slot, value)

    def __deepcopy__(self, memo: dict[int, Any]) -> 'CPUInfo':
        """Return a shallow copy of the instance as an optimized deep copy.

        Since the CPUInfo instance is immutable and composed of immutable components,
        a shallow copy is functionally identical to a deep copy. This method overrides
        the default `copy.deepcopy` behavior to perform a more efficient shallow copy instead.

        :param memo: The memoization dictionary used by `copy.deepcopy`.
                     It is not used in this optimized implementation.
        :return CPUInfo: A new, shallow-copied instance of the CPUInfo.
        """
        # because the CPUInfo is immutable, we can return a copy of self
        # instead of performing a full deep copy.
        return copy(self)
