"""ErrorTags for PythonInfo classes"""
from simplebench.doc_utils import enum_docstrings
from simplebench.exceptions import ErrorTag


@enum_docstrings
class _PythonInfoErrorTag(ErrorTag):
    """ErrorTags for PythonInfo classes"""
    JSON_SCHEMA_VALIDATION_ERROR = "JSON_SCHEMA_VALIDATION_ERROR"
    """JSON schema validation error"""
    INVALID_HASH_ID_TYPE = "INVALID_HASH_ID_TYPE"
    """Invalid hash_id type - must be a string"""
    INVALID_HASH_ID_VALUE = "INVALID_HASH_ID_VALUE"
    """Invalid hash_id value - must be a 64-character hexadecimal string"""
    INVALID_COMPILER_TYPE = "INVALID_COMPILER_TYPE"
    """Invalid compiler type - must be a string"""
    EMPTY_COMPILER_VALUE = "EMPTY_COMPILER_VALUE"
    """Empty compiler value - must be a non-empty string"""
    INVALID_IMPLEMENTATION_TYPE = "INVALID_IMPLEMENTATION_TYPE"
    """Invalid implementation type - must be a string"""
    EMPTY_IMPLEMENTATION_VALUE = "EMPTY_IMPLEMENTATION_VALUE"
    """Empty implementation value - must be a non-empty string"""
    INVALID_IMPLEMENTATION_VERSION_TYPE = "INVALID_IMPLEMENTATION_VERSION_TYPE"
    """Invalid implementation_version type - must be a string"""
    EMPTY_IMPLEMENTATION_VERSION_VALUE = "EMPTY_IMPLEMENTATION_VERSION_VALUE"
    """Empty implementation_version value - must be a non-empty string"""
    INVALID_PYTHON_VERSION_TYPE = "INVALID_PYTHON_VERSION_TYPE"
    """Invalid python_version type - must be a string"""
    EMPTY_PYTHON_VERSION_VALUE = "EMPTY_PYTHON_VERSION_VALUE"
    """Empty python_version value - must be a non-empty string"""
    INVALID_BUILD_TYPE = "INVALID_BUILD_TYPE"
    """Invalid build type - must be a string"""
    EMPTY_BUILD_VALUE = "EMPTY_BUILD_VALUE"
    """Empty build value - must be a non-empty string"""
    INVALID_RELEASE_TYPE = "INVALID_RELEASE_TYPE"
    """Invalid release type - must be a string"""
    EMPTY_RELEASE_VALUE = "EMPTY_RELEASE_VALUE"
    """Empty release value - must be a non-empty string"""
    INVALID_SYSTEM_TYPE = "INVALID_SYSTEM_TYPE"
    """Invalid system type - must be a string"""
    EMPTY_SYSTEM_VALUE = "EMPTY_SYSTEM_VALUE"
    """Empty system value - must be a non-empty string"""
    INVALID_DATA_ARG_TYPE = "INVALID_DATA_ARG_TYPE"
    """Invalid data argument type"""
    INVALID_VERSION_TYPE = "INVALID_VERSION_TYPE"
    """Invalid version type"""
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
    """Unsupported version"""
    INVALID_TYPE_TYPE = "INVALID_TYPE_TYPE"
    """Invalid type type"""
    INVALID_TYPE_VALUE = "INVALID_TYPE_VALUE"
    """Invalid type value"""
    INVALID_DATA_ARG_EXTRA_KEYS = "INVALID_DATA_ARG_EXTRA_KEYS"
    """Invalid data argument extra keys"""
    INVALID_DATA_ARG_MISSING_KEYS = "INVALID_DATA_ARG_MISSING_KEYS"
    """Invalid data argument missing keys"""
