"""Exceptions for JSON stats summary report."""
from simplebench.doc_utils import enum_docstrings
from simplebench.exceptions import ErrorTag

__all__ = []


@enum_docstrings
class _StatsBlockErrorTag(ErrorTag):
    """Error tags for JSON stats summary exceptions."""
    INVALID_HASH_ID_TYPE = "INVALID_HASH_ID_TYPE"
    """The hash_id is not a string."""
    INVALID_HASH_ID_VALUE = "INVALID_HASH_ID_VALUE"
    """The hash_id has an invalid value.
    
    Must either be a 64-character hexadecimal string or an empty string."""
    INVALID_TIMER_TYPE = "INVALID_TIMER_TYPE"
    """The timer is not a string or None."""
    INVALID_TIMER_VALUE = "INVALID_TIMER_VALUE"
    """The timer has an invalid value (cannot be empty)."""
    MEDIAN_AND_MEASUREMENTS_PROVIDED = "MEDIAN_AND_MEASUREMENTS_PROVIDED"
    """Both median and measurements were provided, but only one is allowed."""
    MEAN_AND_MEASUREMENTS_PROVIDED = "MEAN_AND_MEASUREMENTS_PROVIDED"
    """Both mean and measurements were provided, but only one is allowed."""
    STDEV_AND_MEASUREMENTS_PROVIDED = "STDEV_AND_MEASUREMENTS_PROVIDED"
    """Both standard_deviation and measurements were provided, but only one is allowed."""
    RELATIVE_STDEV_AND_MEASUREMENTS_PROVIDED = "RELATIVE_STDEV_AND_MEASUREMENTS_PROVIDED"
    """Both relative_standard_deviation and measurements were provided, but only one is allowed."""
    PERCENTILES_AND_MEASUREMENTS_PROVIDED = "PERCENTILES_AND_MEASUREMENTS_PROVIDED"
    """Both percentiles and measurements were provided, but only one is allowed."""
    MINIMUM_AND_MEASUREMENTS_PROVIDED = "MINIMUM_AND_MEASUREMENTS_PROVIDED"
    """Both minimum and measurements were provided, but only one is allowed."""
    MAXIMUM_AND_MEASUREMENTS_PROVIDED = "MAXIMUM_AND_MEASUREMENTS_PROVIDED"
    """Both maximum and measurements were provided, but only one is allowed."""
    ITERATIONS_AND_MEASUREMENTS_PROVIDED = "ITERATIONS_AND_MEASUREMENTS_PROVIDED"
    """Both iterations and measurements were provided, but only one is allowed."""
    INVALID_STATS_BLOCK_ARGUMENTS = "INVALID_STATS_BLOCK_ARGUMENTS"
    """The arguments provided to StatsBlock are invalid."""
    INVALID_PERCENTILES_ORDER = "INVALID_PERCENTILES_ORDER"
    """The percentiles are not sorted in ascending order."""
    INVALID_MEASUREMENTS_STATE = "INVALID_MEASUREMENTS_STATE"
    """The measurements property is in an invalid state for the requested operation."""
    INVALID_SEMANTIC_TYPE_TYPE = "INVALID_SEMANTIC_TYPE_TYPE"
    """The semantic_type is not a string."""
    INVALID_SEMANTIC_TYPE_VALUE = "INVALID_SEMANTIC_TYPE_VALUE"
    """The semantic_type is not a valid namespaced identifier."""
    IMMUTABLE_VIOLATION = "IMMUTABLE_MEASUREMENTS"
    """The measurements property is immutable once set."""
    TOO_FEW_MEASUREMENTS = "TOO_FEW_MEASUREMENTS"
    """There are too few measurements to compute statistics."""
    ITERATIONS_INCONSISTENT_WITH_MEASUREMENTS = "ITERATIONS_INCONSISTENT_WITH_MEASUREMENTS"
    """The number of iterations does not match the number of measurements."""
    LAZY_PROPERTY_REQUIREMENTS_ERROR = "LAZY_PROPERTY_REQUIREMENTS_ERROR"
    """A lazy property cannot be computed because its requirements are not met."""
    INVALID_MEASUREMENTS_TYPE = "INVALID_MEASUREMENTS_TYPE"
    """The measurements is not a Sequence or None."""
    INVALID_MEASUREMENTS_CONTENT_TYPE = "INVALID_MEASUREMENTS_CONTENT_TYPE"
    """One or more items in measurements are not of type float."""
    JSON_SCHEMA_VALIDATION_ERROR = "JSON_SCHEMA_VALIDATION_ERROR"
    """The JSON data does not conform to the expected schema."""
    INVALID_DATA_ARG_EXTRA_KEYS = "INVALID_DATA_ARG_EXTRA_KEYS"
    """The data argument contains extra keys."""
    INVALID_DATA_ARG_MISSING_KEYS = "INVALID_DATA_ARG_MISSING_KEYS"
    """The data argument is missing required keys."""
    INVALID_DATA_ARG_TYPE = "INVALID_DATA_ARG_TYPE"
    """The data argument is not of type dict."""
    INVALID_NAME_TYPE = "INVALID_NAME_TYPE"
    """The name is not of type string."""
    INVALID_NAME_VALUE = "INVALID_NAME_VALUE"
    """The name has an invalid value. Cannot be an empty string."""
    INVALID_DESCRIPTION_TYPE = "INVALID_DESCRIPTION_TYPE"
    """The description is not of type string."""
    INVALID_DESCRIPTION_VALUE = "INVALID_DESCRIPTION_VALUE"
    """The description has an invalid value."""
    INVALID_PERCENTILES_LENGTH = "INVALID_PERCENTILES_LENGTH"
    """The percentiles list is not 101 items long."""
    INVALID_TYPE_TYPE = "INVALID_TYPE_TYPE"
    """The type is not of type string."""
    INVALID_TYPE_VALUE = "INVALID_TYPE_VALUE"
    """The type has an invalid value."""
    INVALID_UNIT_TYPE = "INVALID_UNIT_TYPE"
    """The unit is not of type string."""
    INVALID_UNIT_VALUE = "INVALID_UNIT_VALUE"
    """The unit has an invalid value. Cannot be an empty string."""
    INVALID_SCALE_TYPE = "INVALID_SCALE_TYPE"
    """The scale is not of type float."""
    INVALID_SCALE_VALUE = "INVALID_SCALE_VALUE"
    """The scale has an invalid value. Must be > 0.0"""
    INVALID_N_TYPE = "INVALID_N_TYPE"
    """The n is not of type integer."""
    INVALID_N_VALUE = "INVALID_N_VALUE"
    """The n has an invalid value. Must be >= 0."""
    INVALID_ITERATIONS_TYPE = "INVALID_ITERATIONS_TYPE"
    """The iterations is not of type integer."""
    INVALID_ITERATIONS_VALUE = "INVALID_ITERATIONS_VALUE"
    """The iterations has an invalid value. Must be >= 1."""
    INVALID_ROUNDS_TYPE = "INVALID_ROUNDS_TYPE"
    """The rounds is not of type integer."""
    INVALID_ROUNDS_VALUE = "INVALID_ROUNDS_VALUE"
    """The rounds has an invalid value. Must be >= 1."""
    INVALID_MEAN_TYPE = "INVALID_MEAN_TYPE"
    """The mean is not of type float."""
    INVALID_MEDIAN_TYPE = "INVALID_MEDIAN_TYPE"
    """The median is not of type float."""
    INVALID_MINIMUM_TYPE = "INVALID_MINIMUM_TYPE"
    """The minimum is not of type float."""
    INVALID_MAXIMUM_TYPE = "INVALID_MAXIMUM_TYPE"
    """The maximum is not of type float."""
    INVALID_STANDARD_DEVIATION_TYPE = "INVALID_STANDARD_DEVIATION_TYPE"
    """The standard_deviation is not of type float."""
    INVALID_STANDARD_DEVIATION_VALUE = "INVALID_STANDARD_DEVIATION_VALUE"
    """The standard_deviation has an invalid value. Must be >= 0."""
    INVALID_RELATIVE_STANDARD_DEVIATION_TYPE = "INVALID_RELATIVE_STANDARD_DEVIATION_TYPE"
    """The relative_standard_deviation is not of type float."""
    INVALID_RELATIVE_STANDARD_DEVIATION_VALUE = "INVALID_RELATIVE_STANDARD_DEVIATION_VALUE"
    """The relative_standard_deviation has an invalid value. Must be >= 0."""
    INVALID_PERCENTILES_TYPE = "INVALID_PERCENTILES_TYPE"
    """The percentiles is not a Sequence."""
    INVALID_PERCENTILES_CONTENT_TYPE = "INVALID_PERCENTILES_CONTENT_TYPE"
    """One or more items in percentiles are not of type float or int."""
    INVALID_VERSION_TYPE = "INVALID_VERSION_TYPE"
    """The version is not of type integer."""
    UNSUPPORTED_VERSION = "UNSUPPORTED_VERSION"
    """The version is not supported."""
